(function () {
    'use strict';
    function esc(value) { var node = document.createElement('div'); node.textContent = value == null ? '' : value; return node.innerHTML; }
    function dateText(value) { var parts = String(value || '').split('-'); return parts.length === 3 ? parts[2] + '/' + parts[1] + '/' + parts[0] : value; }
    function number(value) { return Number(value || 0).toLocaleString('vi-VN'); }
    function post(url, data) { return fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json; charset=utf-8' }, body: JSON.stringify(data) }).then(function (response) { return response.json().then(function (body) { if (!response.ok) throw new Error('Không thể tải dữ liệu.'); return body.d !== undefined ? body.d : body; }); }); }
    function today() { var d = new Date(); return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0'); }
    function shift(value, days) { var d = new Date(value + 'T00:00:00'); d.setDate(d.getDate() + days); return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0'); }
    function init() {
        var page = document.querySelector('.fpd-page'); if (!page) return;
        var endpoint = page.getAttribute('data-endpoint'), airport = document.getElementById('fpdAirport'), operator = document.getElementById('fpdOperator'), date1 = document.getElementById('fpdDate1'), date2 = document.getElementById('fpdDate2'), apply = document.getElementById('fpdApply'), status = document.getElementById('fpdStatus'), body = document.getElementById('fpdBody'), error = document.getElementById('fpdError');
        date1.max = today(); date1.value = today(); date2.value = shift(date1.value, -7);
        function setStatus(message, loading) { status.innerHTML = loading ? '<span class="fpd-spinner" aria-hidden="true"></span> ' + esc(message) : esc(message); status.className = 'fpd-status' + (loading ? '' : ' is-ready'); }
        function renderAirports(values) { airport.innerHTML = '<option value="ALL">Tất cả sân bay</option>' + (values || []).map(function (x) { return '<option value="' + esc(x) + '">' + esc(x) + '</option>'; }).join(''); }
        function renderOperators(values) { operator.innerHTML = '<option value="ALL">Tất cả hãng</option>' + (values || []).map(function (x) { return '<option value="' + esc(x) + '">' + esc(x) + '</option>'; }).join(''); }
        function render(data) {
            document.getElementById('fpdHeadDate1').textContent = dateText(data.date1); document.getElementById('fpdHeadDate2').textContent = dateText(data.date2);
            document.getElementById('fpdLegendDate1').textContent = dateText(data.date1); document.getElementById('fpdLegendDate2').textContent = dateText(data.date2); renderChart(data.airportChart || []);
            var allDifferent = (data.differences.date1 || []).concat(data.differences.date2 || []);
            var rows = [
                ['Tổng số chuyến bay', data.day1.total, data.day2.total, allDifferent.length, null],
                ['Tổng số chuyến bay mùa (SC)', data.day1.seasonal, data.day2.seasonal, allDifferent.filter(function (x) { return String(x.flightType).toUpperCase() === 'SC'; }).length, 'SC'],
                ['Tổng số chuyến bay đột xuất (NO)', data.day1.adHoc, data.day2.adHoc, allDifferent.filter(function (x) { return String(x.flightType).toUpperCase() === 'NO'; }).length, 'NO'],
                ['Tổng số phép bay mùa (SC)', data.day1.seasonalPermits, data.day2.seasonalPermits, null, 'SC', 'PERMIT'],
                ['Tổng số phép bay đột xuất (NO)', data.day1.adHocPermits, data.day2.adHocPermits, null, 'NO', 'PERMIT']
            ];
            body.innerHTML = rows.map(function (row, i) { var permitRow = row[5] === 'PERMIT'; var diff = row[3] == null && !permitRow ? '<span class="fpd-muted">-</span>' : '<div class="fpd-diff">' + (row[3] == null ? '' : '<strong>' + number(row[3]) + '</strong>') + '<button class="fpd-detail-btn" type="button" data-detail="' + i + '">Chi tiết</button></div>'; return '<tr><td>' + (i + 1) + '</td><td>' + esc(row[0]) + '</td><td>' + number(row[1]) + '</td><td>' + number(row[2]) + '</td><td>' + diff + '</td></tr>'; }).join('');
            Array.prototype.forEach.call(body.querySelectorAll('[data-detail]'), function (button) { button.addEventListener('click', function () { var row = rows[Number(button.getAttribute('data-detail'))]; openDetails(data, row[4], row[5]); }); });
            setStatus('Đã cập nhật lúc ' + new Date().toLocaleTimeString('vi-VN'), false);
        }
        function renderChart(items) { var chart = document.getElementById('fpdAirportChart'); if (!items.length) { chart.innerHTML = '<div class="fpd-empty">Không có dữ liệu sân bay.</div>'; return; } var max = Math.max.apply(null, items.map(function (x) { return Math.max(x.date1, x.date2); }).concat([1])); chart.innerHTML = items.map(function (item) { var h1 = Math.max(4, Math.round(item.date1 * 100 / max)); var h2 = Math.max(4, Math.round(item.date2 * 100 / max)); return '<div class="fpd-airport-group"><div class="fpd-bars"><div class="fpd-bar fpd-bar-day1" style="height:' + h1 + '%"><strong>' + number(item.date1) + '</strong></div><div class="fpd-bar fpd-bar-day2" style="height:' + h2 + '%"><strong>' + number(item.date2) + '</strong></div></div><b>' + esc(item.airport) + '</b></div>'; }).join(''); }
        function renderDetails(target, rows, permitMode) { target.innerHTML = rows.length ? rows.map(function (row, index) { return permitMode ? '<tr><td>' + (index + 1) + '</td><td>' + esc(row.permNbr) + '</td></tr>' : '<tr><td>' + esc(row.callsign) + '</td><td>' + esc(row.fromAirp) + '</td><td>' + esc(row.toAirp) + '</td><td>' + esc(row.etd) + '</td><td>' + esc(row.eta) + '</td></tr>'; }).join('') : '<tr><td colspan="' + (permitMode ? '2' : '5') + '" class="fpd-detail-empty">Không có dữ liệu.</td></tr>'; }
        function openDetails(data, flightType, detailMode) { var modal = document.getElementById('fpdModal'); var permitMode = detailMode === 'PERMIT'; var filter = function (row) { return !flightType || String(row.flightType).toUpperCase() === flightType; }; var source1 = permitMode ? (data.permits && (flightType === 'SC' ? data.permits.scDate1 : data.permits.noDate1) || []) : (data.differences.date1 || []); var source2 = permitMode ? (data.permits && (flightType === 'SC' ? data.permits.scDate2 : data.permits.noDate2) || []) : (data.differences.date2 || []); var list1 = permitMode ? source1 : source1.filter(filter); var list2 = permitMode ? source2 : source2.filter(filter); var headers = modal.querySelectorAll('.fpd-detail-wrap thead'); Array.prototype.forEach.call(headers, function (head) { head.innerHTML = permitMode ? '<tr><th>STT</th><th>PERMNBR</th></tr>' : '<tr><th>CALLSIGN</th><th>FROM_AIRP</th><th>TO_AIRP</th><th>ETD</th><th>ETA</th></tr>'; }); document.getElementById('fpdModalTitle').textContent = permitMode ? 'Các phép bay không trùng' : 'Các chuyến bay không trùng'; document.getElementById('fpdModalDate1').textContent = dateText(data.date1) + ' · ngày 1'; document.getElementById('fpdModalDate2').textContent = dateText(data.date2) + ' · ngày 2'; document.getElementById('fpdModalInfo').textContent = 'Tổng cộng ' + number(list1.length + list2.length) + (permitMode ? ' phép bay' : ' chuyến bay khác') + (flightType ? ' loại ' + flightType : '') + '.'; renderDetails(document.getElementById('fpdDetails1'), list1, permitMode); renderDetails(document.getElementById('fpdDetails2'), list2, permitMode); modal.hidden = false; document.getElementById('fpdClose').focus(); }
        function load() { error.hidden = true; body.innerHTML = '<tr><td colspan="5" class="fpd-empty">Đang tải dữ liệu...</td></tr>'; setStatus('Đang tải dữ liệu...', true); post(endpoint, { date1: date1.value, airport: airport.value, oper: operator.value }).then(render).catch(function (e) { error.textContent = e.message || 'Không thể tải dữ liệu.'; error.hidden = false; setStatus('Không tải được dữ liệu', false); body.innerHTML = '<tr><td colspan="5" class="fpd-empty">Không có dữ liệu để hiển thị.</td></tr>'; }); }
        date1.addEventListener('change', function () { date2.value = shift(date1.value, -7); }); apply.addEventListener('click', load); document.getElementById('fpdClose').addEventListener('click', function () { document.getElementById('fpdModal').hidden = true; }); document.getElementById('fpdModal').addEventListener('click', function (e) { if (e.target === this) this.hidden = true; }); document.addEventListener('keydown', function (e) { if (e.key === 'Escape') document.getElementById('fpdModal').hidden = true; });
        post(endpoint.replace(/GetComparison$/, 'GetAirports'), {}).then(renderAirports).catch(function () { renderAirports([]); }); post(endpoint.replace(/GetComparison$/, 'GetOperators'), {}).then(renderOperators).catch(function () { renderOperators([]); }); load();
    }
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
}());
