//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjApplication.Permission
{
    public partial class SearchPermissionAdv
    {
    }
}
