/*
  Sửa lỗi biên dịch khi bổ sung GET_FINISHED_FLIGHTS_MINITARY vào
  package A_TEST_SEARCH.

  Lưu ý:
  - Giữ nguyên tên MINITARY để không làm thay đổi hợp đồng API hiện tại.
  - p_PURPOSE chỉ được khai báo một lần.
  - Package specification chỉ chứa declaration.
  - Package body chỉ chứa một implementation, không đặt thêm một forward
    declaration trùng ngay trước implementation.
*/

/* ================================================================
   1. Declaration đặt trong PACKAGE A_TEST_SEARCH AS
   ================================================================ */
PROCEDURE GET_FINISHED_FLIGHTS_MINITARY
(
    p_FLIGHTDATE IN T_FINISHFLIGHTS_MILITARY.FLIGHTDATE%TYPE DEFAULT NULL,
    p_CALLSIGN   IN T_FINISHFLIGHTS_MILITARY.CALLSIGN%TYPE   DEFAULT NULL,
    p_P_TYPE     IN T_FINISHFLIGHTS_MILITARY.P_TYPE%TYPE     DEFAULT NULL,
    p_FROM_AIRP  IN T_FINISHFLIGHTS_MILITARY.FROM_AIRP%TYPE  DEFAULT NULL,
    p_TO_AIRP    IN T_FINISHFLIGHTS_MILITARY.TO_AIRP%TYPE    DEFAULT NULL,
    p_ETD        IN T_FINISHFLIGHTS_MILITARY.ETD%TYPE        DEFAULT NULL,
    p_ETA        IN T_FINISHFLIGHTS_MILITARY.ETA%TYPE        DEFAULT NULL,
    p_ATD        IN T_FINISHFLIGHTS_MILITARY.ATD%TYPE        DEFAULT NULL,
    p_ATA        IN T_FINISHFLIGHTS_MILITARY.ATA%TYPE        DEFAULT NULL,
    p_VIA        IN T_FINISHFLIGHTS_MILITARY.VIA%TYPE        DEFAULT NULL,
    p_REMARK     IN T_FINISHFLIGHTS_MILITARY.REMARK%TYPE     DEFAULT NULL,
    p_FLIGHT_ID  IN T_FINISHFLIGHTS_MILITARY.FLIGHT_ID%TYPE  DEFAULT NULL,
    p_OPER       IN T_FINISHFLIGHTS_MILITARY.OPER%TYPE       DEFAULT NULL,
    p_REGIS      IN T_FINISHFLIGHTS_MILITARY.REGIS%TYPE      DEFAULT NULL,
    p_PURPOSE    IN T_FINISHFLIGHTS_MILITARY.PURPOSE%TYPE    DEFAULT NULL,
    p_RCRAFT     IN T_FINISHFLIGHTS_MILITARY.RCRAFT%TYPE     DEFAULT NULL,
    p_FCRAFT     IN T_FINISHFLIGHTS_MILITARY.FCRAFT%TYPE     DEFAULT NULL,
    p_FPLVIA     IN T_FINISHFLIGHTS_MILITARY.FPLVIA%TYPE     DEFAULT NULL,
    p_KHUNGGIO1  IN VARCHAR2,
    p_KHUNGGIO2  IN VARCHAR2,
    p_PageSize   IN INT,
    p_PageIndex  IN INT,
    p_StartDate  IN VARCHAR2,
    p_FinishDate IN VARCHAR2,
    P_OUT_CURSOR OUT T_CURSOR
);

/* ================================================================
   2. Implementation đặt trong PACKAGE BODY A_TEST_SEARCH
   ================================================================ */
PROCEDURE GET_FINISHED_FLIGHTS_MINITARY
(
    p_FLIGHTDATE IN T_FINISHFLIGHTS_MILITARY.FLIGHTDATE%TYPE DEFAULT NULL,
    p_CALLSIGN   IN T_FINISHFLIGHTS_MILITARY.CALLSIGN%TYPE   DEFAULT NULL,
    p_P_TYPE     IN T_FINISHFLIGHTS_MILITARY.P_TYPE%TYPE     DEFAULT NULL,
    p_FROM_AIRP  IN T_FINISHFLIGHTS_MILITARY.FROM_AIRP%TYPE  DEFAULT NULL,
    p_TO_AIRP    IN T_FINISHFLIGHTS_MILITARY.TO_AIRP%TYPE    DEFAULT NULL,
    p_ETD        IN T_FINISHFLIGHTS_MILITARY.ETD%TYPE        DEFAULT NULL,
    p_ETA        IN T_FINISHFLIGHTS_MILITARY.ETA%TYPE        DEFAULT NULL,
    p_ATD        IN T_FINISHFLIGHTS_MILITARY.ATD%TYPE        DEFAULT NULL,
    p_ATA        IN T_FINISHFLIGHTS_MILITARY.ATA%TYPE        DEFAULT NULL,
    p_VIA        IN T_FINISHFLIGHTS_MILITARY.VIA%TYPE        DEFAULT NULL,
    p_REMARK     IN T_FINISHFLIGHTS_MILITARY.REMARK%TYPE     DEFAULT NULL,
    p_FLIGHT_ID  IN T_FINISHFLIGHTS_MILITARY.FLIGHT_ID%TYPE  DEFAULT NULL,
    p_OPER       IN T_FINISHFLIGHTS_MILITARY.OPER%TYPE       DEFAULT NULL,
    p_REGIS      IN T_FINISHFLIGHTS_MILITARY.REGIS%TYPE      DEFAULT NULL,
    p_PURPOSE    IN T_FINISHFLIGHTS_MILITARY.PURPOSE%TYPE    DEFAULT NULL,
    p_RCRAFT     IN T_FINISHFLIGHTS_MILITARY.RCRAFT%TYPE     DEFAULT NULL,
    p_FCRAFT     IN T_FINISHFLIGHTS_MILITARY.FCRAFT%TYPE     DEFAULT NULL,
    p_FPLVIA     IN T_FINISHFLIGHTS_MILITARY.FPLVIA%TYPE     DEFAULT NULL,
    p_KHUNGGIO1  IN VARCHAR2,
    p_KHUNGGIO2  IN VARCHAR2,
    p_PageSize   IN INT,
    p_PageIndex  IN INT,
    p_StartDate  IN VARCHAR2,
    p_FinishDate IN VARCHAR2,
    P_OUT_CURSOR OUT T_CURSOR
)
IS
BEGIN
    /*
      Bước này giữ nguyên nghiệp vụ của implementation được bổ sung ban đầu.
      Bộ lọc và phân trang sẽ được triển khai riêng sau khi xác nhận hợp đồng
      dữ liệu của các tham số KHUNGGIO/StartDate/FinishDate.
    */
    OPEN P_OUT_CURSOR FOR
        SELECT *
        FROM T_FINISHFLIGHTS_MILITARY;
END GET_FINISHED_FLIGHTS_MINITARY;
