-- ============================================================================
-- Store package cho trang ReportNew/FlightPlanDailyComparison.aspx
-- (so sanh ke hoach bay ngay hien tai voi cung ky tuan truoc).
-- API:
--   packageName=DAYPLAN_COMPARE_PKG&storeName=GET_DAY_FLIGHTS
--   packageName=DAYPLAN_COMPARE_PKG&storeName=GET_AIRPORTS
--   packageName=DAYPLAN_COMPARE_PKG&storeName=GET_OPERATORS
--
-- Nguon: T_DAY_FLIGHTS (chuyen co phep, PERMNBR <> 'NOPERM').
-- Chi doc du lieu. Script chay lai nhieu lan duoc.
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF

DECLARE
    v_count PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'T_DAY_FLIGHTS';
    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20993, 'Thieu bang T_DAY_FLIGHTS');
    END IF;
    DBMS_OUTPUT.PUT_LINE('DAYPLAN_COMPARE_PKG precheck: OK');
END;
/

CREATE OR REPLACE PACKAGE DAYPLAN_COMPARE_PKG AS
    TYPE T_CURSOR IS REF CURSOR;

    -- Chuyen bay co phep cua mot ngay. P_AIRPORT/P_OPER: NULL hoac 'ALL' = khong loc.
    PROCEDURE GET_DAY_FLIGHTS
    (
        P_FLIGHT_DATE IN VARCHAR2,
        P_AIRPORT     IN VARCHAR2 DEFAULT NULL,
        P_OPER        IN VARCHAR2 DEFAULT NULL,
        P_OUT_CURSOR  OUT T_CURSOR
    );

    PROCEDURE GET_AIRPORTS
    (
        P_OUT_CURSOR OUT T_CURSOR
    );

    PROCEDURE GET_OPERATORS
    (
        P_OUT_CURSOR OUT T_CURSOR
    );
END DAYPLAN_COMPARE_PKG;
/

CREATE OR REPLACE PACKAGE BODY DAYPLAN_COMPARE_PKG AS

    FUNCTION PARSE_DATE(P_VALUE IN VARCHAR2, P_NAME IN VARCHAR2) RETURN DATE
    IS
        V_VALUE VARCHAR2(40) := TRIM(P_VALUE);
    BEGIN
        IF REGEXP_LIKE(V_VALUE, '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN
            RETURN TO_DATE(V_VALUE, 'FXYYYY-MM-DD');
        ELSIF REGEXP_LIKE(V_VALUE, '^[0-9]{2}-[0-9]{2}-[0-9]{4}$') THEN
            RETURN TO_DATE(V_VALUE, 'FXDD-MM-YYYY');
        ELSIF REGEXP_LIKE(V_VALUE, '^[0-9]{2}/[0-9]{2}/[0-9]{4}$') THEN
            RETURN TO_DATE(V_VALUE, 'FXDD/MM/YYYY');
        END IF;
        RAISE_APPLICATION_ERROR(-20994, P_NAME || ' phai dung dinh dang YYYY-MM-DD hoac DD-MM-YYYY');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -20994 THEN RAISE; END IF;
            RAISE_APPLICATION_ERROR(-20994, P_NAME || ' khong phai la ngay hop le');
    END PARSE_DATE;

    FUNCTION NORMALIZE_FILTER(P_VALUE IN VARCHAR2) RETURN VARCHAR2
    IS
        V_VALUE VARCHAR2(4000) := UPPER(TRIM(P_VALUE));
    BEGIN
        IF V_VALUE IS NULL OR V_VALUE = 'ALL' THEN RETURN NULL; END IF;
        RETURN V_VALUE;
    END NORMALIZE_FILTER;

    PROCEDURE WRITE_ERROR(P_ACTION IN VARCHAR2) IS
    BEGIN
        PROCESS_PKG.ADD_ERROR_LOG
        (
            P_ACTION,
            SQLCODE,
            SUBSTR(SQLERRM || CHR(10) || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 1, 200)
        );
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END WRITE_ERROR;

    PROCEDURE GET_DAY_FLIGHTS
    (
        P_FLIGHT_DATE IN VARCHAR2,
        P_AIRPORT     IN VARCHAR2 DEFAULT NULL,
        P_OPER        IN VARCHAR2 DEFAULT NULL,
        P_OUT_CURSOR  OUT T_CURSOR
    )
    IS
        V_DATE    DATE;
        V_AIRPORT VARCHAR2(100);
        V_OPER    VARCHAR2(100);
    BEGIN
        V_DATE := PARSE_DATE(P_FLIGHT_DATE, 'P_FLIGHT_DATE');
        V_AIRPORT := NORMALIZE_FILTER(P_AIRPORT);
        V_OPER := NORMALIZE_FILTER(P_OPER);

        OPEN P_OUT_CURSOR FOR
            SELECT FLIGHTNBR, FROM_AIRP, TO_AIRP, ETD, ETA, FLIGHT_TYPE, OPER_ID, PERMNBR, PERM_ID
              FROM T_DAY_FLIGHTS
             WHERE FLIGHTDATE >= V_DATE AND FLIGHTDATE < V_DATE + 1
               AND PERMNBR IS NOT NULL AND UPPER(TRIM(PERMNBR)) <> 'NOPERM'
               AND (V_AIRPORT IS NULL OR UPPER(TRIM(FROM_AIRP)) = V_AIRPORT OR UPPER(TRIM(TO_AIRP)) = V_AIRPORT)
               AND (V_OPER IS NULL OR UPPER(TRIM(OPER_ID)) = V_OPER);
    EXCEPTION
        WHEN OTHERS THEN
            WRITE_ERROR('DAYPLAN_COMPARE_PKG.GET_DAY_FLIGHTS');
            RAISE;
    END GET_DAY_FLIGHTS;

    PROCEDURE GET_AIRPORTS
    (
        P_OUT_CURSOR OUT T_CURSOR
    )
    IS
    BEGIN
        OPEN P_OUT_CURSOR FOR
            SELECT AIRPORT FROM (
                SELECT DISTINCT UPPER(TRIM(FROM_AIRP)) AIRPORT FROM T_DAY_FLIGHTS WHERE FROM_AIRP IS NOT NULL
                UNION SELECT DISTINCT UPPER(TRIM(TO_AIRP)) AIRPORT FROM T_DAY_FLIGHTS WHERE TO_AIRP IS NOT NULL
            ) WHERE AIRPORT IS NOT NULL ORDER BY AIRPORT;
    EXCEPTION
        WHEN OTHERS THEN
            WRITE_ERROR('DAYPLAN_COMPARE_PKG.GET_AIRPORTS');
            RAISE;
    END GET_AIRPORTS;

    PROCEDURE GET_OPERATORS
    (
        P_OUT_CURSOR OUT T_CURSOR
    )
    IS
    BEGIN
        OPEN P_OUT_CURSOR FOR
            SELECT DISTINCT UPPER(TRIM(OPER_ID)) OPER_ID
              FROM T_DAY_FLIGHTS
             WHERE OPER_ID IS NOT NULL
             ORDER BY OPER_ID;
    EXCEPTION
        WHEN OTHERS THEN
            WRITE_ERROR('DAYPLAN_COMPARE_PKG.GET_OPERATORS');
            RAISE;
    END GET_OPERATORS;
END DAYPLAN_COMPARE_PKG;
/

DECLARE
    V_COUNT PLS_INTEGER;
BEGIN
    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'DAYPLAN_COMPARE_PKG'
       AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
       AND STATUS = 'VALID';

    IF V_COUNT <> 2 THEN
        RAISE_APPLICATION_ERROR(-20995, 'DAYPLAN_COMPARE_PKG chua VALID day du');
    END IF;

    DBMS_OUTPUT.PUT_LINE('DAYPLAN_COMPARE_PKG deployment verify: OK');
END;
/

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'DAYPLAN_COMPARE_PKG'
 ORDER BY OBJECT_TYPE;
