SET LONG 10000;
SET LINESIZE 240;
SET PAGESIZE 200;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('TRG_TDF_GOINGON_ACTION_HIS', 'A_TEST_SEARCH')
 ORDER BY OBJECT_NAME, OBJECT_TYPE;

SELECT NAME, TYPE, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME IN ('TRG_TDF_GOINGON_ACTION_HIS', 'A_TEST_SEARCH')
 ORDER BY NAME, TYPE, SEQUENCE;

SELECT CONSTRAINT_NAME, STATUS, SEARCH_CONDITION
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'T_DAYFLIGHTS_ACTION_HISTORY'
   AND CONSTRAINT_NAME = 'CK_TDF_ACTION_HIS_TYPE';

SELECT *
  FROM
  (
      SELECT HISTORY_ID,
             SOURCE_ROW_ID,
             FLIGHT_ID,
             ACTION_TYPE,
             CALLSIGN,
             TO_CHAR(FLIGHTDATE, 'DD-MM-YYYY') FLIGHTDATE,
             ACTION_USER,
             DBMS_LOB.SUBSTR(CHANGE_DETAIL, 4000, 1) CHANGE_DETAIL,
             ACTION_DATE
        FROM T_DAYFLIGHTS_ACTION_HISTORY
       WHERE ACTION_TYPE = 'FINISH'
       ORDER BY HISTORY_ID DESC
  )
 WHERE ROWNUM <= 20;
