-- AI notification integration. Run before deploying the new web assembly.
-- No API credentials or guessed recipient mappings belong in this migration.
-- The application owns transactions for AI_NOTIFICATION_PKG mutations.

DECLARE
    V_COUNT NUMBER;
BEGIN
    FOR T IN (SELECT COLUMN_VALUE NAME FROM TABLE(SYS.ODCIVARCHAR2LIST(
        'T_NOTIFICATION', 'T_NOTIFICATION_TARGET', 'T_NOTIFICATION_READ', 'T_USERS'))) LOOP
        SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = T.NAME;
        IF V_COUNT <> 1 THEN RAISE_APPLICATION_ERROR(-20140, 'Missing table ' || T.NAME); END IF;
    END LOOP;
END;
/

-- Include the additive 20260804/20260824 prerequisites: deployed DBs may lag git.
DECLARE
    PROCEDURE ADD_COLUMN(P_NAME VARCHAR2, P_DEFINITION VARCHAR2) IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = 'T_NOTIFICATION' AND COLUMN_NAME = P_NAME;
        IF V_COUNT = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE T_NOTIFICATION ADD ' || P_DEFINITION;
        END IF;
    END;
BEGIN
    ADD_COLUMN('SOURCE_TYPE', 'SOURCE_TYPE VARCHAR2(30 CHAR)');
    ADD_COLUMN('SOURCE_KEY', 'SOURCE_KEY VARCHAR2(80 CHAR)');
    ADD_COLUMN('SOURCE_HASH', 'SOURCE_HASH VARCHAR2(80 CHAR)');
    ADD_COLUMN('AI_RECIPIENT_ID', 'AI_RECIPIENT_ID VARCHAR2(320 CHAR)');
END;
/

BEGIN
    UPDATE T_NOTIFICATION SET SOURCE_HASH = SOURCE_KEY
    WHERE SOURCE_TYPE = 'EMAIL_API' AND SOURCE_HASH IS NULL AND SOURCE_KEY IS NOT NULL;
    COMMIT;
END;
/

DECLARE
    V_COUNT NUMBER;
BEGIN
    -- This index can also be function-based on older installations.
    SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UX_T_NOTIFICATION_SOURCE';
    IF V_COUNT > 0 THEN EXECUTE IMMEDIATE 'DROP INDEX UX_T_NOTIFICATION_SOURCE'; END IF;
    SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UX_T_NOTIFICATION_SOURCE_HASH';
    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_T_NOTIFICATION_SOURCE_HASH ON T_NOTIFICATION(SOURCE_HASH)';
    END IF;
END;
/

BEGIN
    UPDATE T_NOTIFICATION SET SOURCE_TYPE = 'email', SOURCE_KEY = '1'
    WHERE SOURCE_TYPE = 'EMAIL_API' AND SOURCE_HASH IS NOT NULL;
    -- Legacy AI rows must never remain broadcast. Replay supplies real metadata.
    UPDATE T_NOTIFICATION SET TARGET_TYPE = 1 WHERE SOURCE_TYPE = 'AI';
    COMMIT;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_AI_RECIPIENT_MAP (
        RECIPIENT_ID VARCHAR2(320 CHAR) NOT NULL,
        USER_ID NUMBER NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_T_AI_RECIPIENT_MAP PRIMARY KEY (RECIPIENT_ID, USER_ID),
        CONSTRAINT CK_AI_RECIPIENT_MAP_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
        CONSTRAINT CK_AI_RECIPIENT_MAP_USER CHECK (USER_ID > 0),
        CONSTRAINT CK_AI_RECIPIENT_MAP_ID CHECK (TRIM(RECIPIENT_ID) IS NOT NULL
            AND RECIPIENT_ID = CASE WHEN INSTR(RECIPIENT_ID, ''@'') > 0
                THEN LOWER(TRIM(RECIPIENT_ID)) ELSE RECIPIENT_ID END))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/

-- T_USERS.USERID has no unique constraint on existing installations; avoid
-- adding a foreign key that cannot compile or modifying legacy user ownership.
-- Both explicit and automatic mappings require an active user at read time.
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE T_AI_NOTIFICATION_SYNC (
        SOURCE_NAME VARCHAR2(30 CHAR) NOT NULL,
        LAST_ID NUMBER(19) DEFAULT 0 NOT NULL,
        LAST_POLL_AT TIMESTAMP NULL,
        AUDIENCE_MODE VARCHAR2(20 CHAR) DEFAULT ''ALL_USERS'' NOT NULL,
        CONSTRAINT PK_T_AI_NOTIFICATION_SYNC PRIMARY KEY (SOURCE_NAME),
        CONSTRAINT CK_AI_NOTIFICATION_SYNC_ID CHECK (LAST_ID >= 0),
        CONSTRAINT CK_AI_NOTIFICATION_AUDIENCE CHECK (AUDIENCE_MODE IN (''ALL_USERS'', ''MAPPED'')))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/

-- Seed only once: rerunning a migration must not rewind an established cursor.
BEGIN
    MERGE INTO T_AI_NOTIFICATION_SYNC D
    USING (SELECT 'NL2SQL' SOURCE_NAME FROM DUAL) S ON (S.SOURCE_NAME = D.SOURCE_NAME)
    WHEN NOT MATCHED THEN INSERT (SOURCE_NAME, LAST_ID, LAST_POLL_AT, AUDIENCE_MODE)
    VALUES (S.SOURCE_NAME, 0, NULL, 'ALL_USERS');
    COMMIT;
END;
/

CREATE OR REPLACE PACKAGE AI_NOTIFICATION_PKG AS
    TYPE T_CURSOR IS REF CURSOR;
    FUNCTION CAN_RECEIVE(P_RECIPIENT_ID IN VARCHAR2, P_USER_ID IN NUMBER) RETURN NUMBER;
    PROCEDURE GET_STATE(P_USER_ID IN NUMBER, P_OUT_CURSOR OUT T_CURSOR);
    PROCEDURE GET_PAGE(P_USER_ID IN NUMBER, P_STATUS IN NUMBER,
        P_PAGE_INDEX IN NUMBER, P_PAGE_SIZE IN NUMBER, P_SOURCE_TYPE IN VARCHAR2,
        P_DATA_CURSOR OUT T_CURSOR, P_TOTAL_CURSOR OUT T_CURSOR);
    PROCEDURE MARK_READ(P_USER_ID IN NUMBER, P_ID IN NUMBER, P_UPDATED_COUNT OUT NUMBER);
    PROCEDURE MARK_ALL_READ(P_USER_ID IN NUMBER, P_SOURCE_TYPE IN VARCHAR2,
        P_UPDATED_COUNT OUT NUMBER);
    PROCEDURE RECONCILE_TARGETS;
END AI_NOTIFICATION_PKG;
/

CREATE OR REPLACE PACKAGE BODY AI_NOTIFICATION_PKG AS
    FUNCTION CAN_RECEIVE(P_RECIPIENT_ID IN VARCHAR2, P_USER_ID IN NUMBER) RETURN NUMBER IS
        V_COUNT NUMBER;
        V_USER_ID NUMBER;
        V_MODE VARCHAR2(20);
        V_RECIPIENT T_AI_RECIPIENT_MAP.RECIPIENT_ID%TYPE;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM T_USERS
        WHERE USERID = P_USER_ID AND USERID > 0 AND USERACTIVE = 1;
        IF V_COUNT = 0 THEN RETURN 0; END IF;
        BEGIN
            SELECT AUDIENCE_MODE INTO V_MODE FROM T_AI_NOTIFICATION_SYNC WHERE SOURCE_NAME = 'NL2SQL';
        EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 0;
        END;
        IF V_MODE = 'ALL_USERS' THEN RETURN 1; END IF;
        IF V_MODE <> 'MAPPED' OR P_RECIPIENT_ID IS NULL THEN RETURN 0; END IF;
        V_RECIPIENT := CASE WHEN INSTR(P_RECIPIENT_ID, '@') > 0
            THEN LOWER(TRIM(P_RECIPIENT_ID)) ELSE P_RECIPIENT_ID END;
        SELECT COUNT(*) INTO V_COUNT FROM T_AI_RECIPIENT_MAP WHERE RECIPIENT_ID = V_RECIPIENT;
        IF V_COUNT > 0 THEN
            SELECT COUNT(*) INTO V_COUNT FROM T_AI_RECIPIENT_MAP
            WHERE RECIPIENT_ID = V_RECIPIENT AND USER_ID = P_USER_ID AND IS_ACTIVE = 1;
            RETURN CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;
        END IF;
        IF INSTR(V_RECIPIENT, '@') = 0 THEN RETURN 0; END IF;
        SELECT COUNT(*), MIN(USERID) INTO V_COUNT, V_USER_ID FROM T_USERS
        WHERE USERACTIVE = 1 AND USERID > 0 AND LOWER(TRIM(USEREMAIL)) = V_RECIPIENT;
        RETURN CASE WHEN V_COUNT = 1 AND V_USER_ID = P_USER_ID THEN 1 ELSE 0 END;
    END CAN_RECEIVE;

    PROCEDURE VALIDATE_USER(P_USER_ID IN NUMBER) IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM T_USERS
        WHERE USERID = P_USER_ID AND USERID > 0 AND USERACTIVE = 1;
        IF V_COUNT = 0 THEN RAISE_APPLICATION_ERROR(-20141, 'Active USER_ID is required.'); END IF;
    END;

    FUNCTION NORMALIZE_SOURCE(P_SOURCE_TYPE IN VARCHAR2) RETURN VARCHAR2 IS
        V_SOURCE VARCHAR2(30) := NVL(UPPER(TRIM(P_SOURCE_TYPE)), 'ALL');
    BEGIN
        IF V_SOURCE = 'AI_QUERY' THEN V_SOURCE := 'AI'; END IF;
        IF V_SOURCE NOT IN ('ALL', 'AI') THEN
            RAISE_APPLICATION_ERROR(-20142, 'Unsupported notification source filter.');
        END IF;
        RETURN V_SOURCE;
    END;

    PROCEDURE GET_STATE(P_USER_ID IN NUMBER, P_OUT_CURSOR OUT T_CURSOR) IS
    BEGIN
        VALIDATE_USER(P_USER_ID);
        OPEN P_OUT_CURSOR FOR
            SELECT ID, TITLE, CONTENT, DATETIME, SOURCE_TYPE, SOURCE_KEY,
                   AI_RECIPIENT_ID, STATUS, UNREAD_COUNT, AI_UNREAD_COUNT
            FROM (
                SELECT V.*, COUNT(*) OVER () UNREAD_COUNT,
                       SUM(CASE WHEN SOURCE_TYPE = 'AI' THEN 1 ELSE 0 END) OVER () AI_UNREAD_COUNT
                FROM (
                    SELECT N.ID, N.TITLE, N.CONTENT, N.DATETIME, N.SOURCE_TYPE, N.SOURCE_KEY,
                           N.AI_RECIPIENT_ID, P_USER_ID USER_ID,
                           CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
                    FROM T_NOTIFICATION N
                    LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = P_USER_ID
                    WHERE (N.TARGET_TYPE = 0 OR EXISTS (SELECT 1 FROM T_NOTIFICATION_TARGET T
                               WHERE T.NOTIFICATION_ID = N.ID AND T.USER_ID = P_USER_ID))
                      AND (NVL(N.SOURCE_TYPE, '~') <> 'AI'
                           OR (N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, P_USER_ID) = 1))
                ) V
                WHERE USER_ID = P_USER_ID AND STATUS = 0
                ORDER BY DATETIME DESC, ID DESC
            ) WHERE ROWNUM <= 50;
    END;

    PROCEDURE GET_PAGE(P_USER_ID IN NUMBER, P_STATUS IN NUMBER,
        P_PAGE_INDEX IN NUMBER, P_PAGE_SIZE IN NUMBER, P_SOURCE_TYPE IN VARCHAR2,
        P_DATA_CURSOR OUT T_CURSOR, P_TOTAL_CURSOR OUT T_CURSOR) IS
        V_SOURCE VARCHAR2(30) := NORMALIZE_SOURCE(P_SOURCE_TYPE);
        V_STATUS NUMBER := CASE WHEN P_STATUS IN (0, 1) THEN P_STATUS ELSE -1 END;
        V_PAGE_INDEX NUMBER := GREATEST(TRUNC(NVL(P_PAGE_INDEX, 1)), 1);
        V_PAGE_SIZE NUMBER := LEAST(GREATEST(TRUNC(NVL(P_PAGE_SIZE, 100)), 1), 100);
    BEGIN
        VALIDATE_USER(P_USER_ID);
        OPEN P_DATA_CURSOR FOR
            SELECT ID, TITLE, CONTENT, DATETIME, SOURCE_TYPE, SOURCE_KEY, AI_RECIPIENT_ID, STATUS
            FROM (
                SELECT V.*, ROW_NUMBER() OVER (ORDER BY DATETIME DESC, ID DESC) ROW_NUMBER_VALUE
                FROM (
                    SELECT N.ID, N.TITLE, N.CONTENT, N.DATETIME, N.SOURCE_TYPE, N.SOURCE_KEY,
                           N.AI_RECIPIENT_ID, P_USER_ID USER_ID,
                           CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
                    FROM T_NOTIFICATION N
                    LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = P_USER_ID
                    WHERE (N.TARGET_TYPE = 0 OR EXISTS (SELECT 1 FROM T_NOTIFICATION_TARGET T
                               WHERE T.NOTIFICATION_ID = N.ID AND T.USER_ID = P_USER_ID))
                      AND (NVL(N.SOURCE_TYPE, '~') <> 'AI'
                           OR (N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, P_USER_ID) = 1))
                ) V
                WHERE USER_ID = P_USER_ID AND (V_STATUS = -1 OR STATUS = V_STATUS)
                  AND (V_SOURCE = 'ALL' OR SOURCE_TYPE = V_SOURCE)
            ) WHERE ROW_NUMBER_VALUE BETWEEN ((V_PAGE_INDEX - 1) * V_PAGE_SIZE) + 1 AND V_PAGE_INDEX * V_PAGE_SIZE
            ORDER BY ROW_NUMBER_VALUE;
        OPEN P_TOTAL_CURSOR FOR
            SELECT COUNT(CASE WHEN (V_STATUS = -1 OR STATUS = V_STATUS)
                               AND (V_SOURCE = 'ALL' OR SOURCE_TYPE = V_SOURCE) THEN 1 END) TOTAL_COUNT,
                   COUNT(CASE WHEN STATUS = 0 THEN 1 END) UNREAD_COUNT,
                   COUNT(CASE WHEN STATUS = 0 AND SOURCE_TYPE = 'AI' THEN 1 END) AI_UNREAD_COUNT
            FROM (
                    SELECT N.ID, N.TITLE, N.CONTENT, N.DATETIME, N.SOURCE_TYPE, N.SOURCE_KEY,
                           N.AI_RECIPIENT_ID, P_USER_ID USER_ID,
                           CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
                    FROM T_NOTIFICATION N
                    LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = P_USER_ID
                    WHERE (N.TARGET_TYPE = 0 OR EXISTS (SELECT 1 FROM T_NOTIFICATION_TARGET T
                               WHERE T.NOTIFICATION_ID = N.ID AND T.USER_ID = P_USER_ID))
                      AND (NVL(N.SOURCE_TYPE, '~') <> 'AI'
                           OR (N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, P_USER_ID) = 1))
                ) WHERE USER_ID = P_USER_ID;
    END;

    PROCEDURE MARK_READ(P_USER_ID IN NUMBER, P_ID IN NUMBER, P_UPDATED_COUNT OUT NUMBER) IS
    BEGIN
        VALIDATE_USER(P_USER_ID);
        INSERT INTO T_NOTIFICATION_READ (NOTIFICATION_ID, USER_ID)
        SELECT ID, P_USER_ID FROM (
                    SELECT N.ID, N.TITLE, N.CONTENT, N.DATETIME, N.SOURCE_TYPE, N.SOURCE_KEY,
                           N.AI_RECIPIENT_ID, P_USER_ID USER_ID,
                           CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
                    FROM T_NOTIFICATION N
                    LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = P_USER_ID
                    WHERE (N.TARGET_TYPE = 0 OR EXISTS (SELECT 1 FROM T_NOTIFICATION_TARGET T
                               WHERE T.NOTIFICATION_ID = N.ID AND T.USER_ID = P_USER_ID))
                      AND (NVL(N.SOURCE_TYPE, '~') <> 'AI'
                           OR (N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, P_USER_ID) = 1))
                )
        WHERE USER_ID = P_USER_ID AND ID = P_ID AND STATUS = 0;
        P_UPDATED_COUNT := SQL%ROWCOUNT;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN P_UPDATED_COUNT := 0;
    END;

    PROCEDURE MARK_ALL_READ(P_USER_ID IN NUMBER, P_SOURCE_TYPE IN VARCHAR2,
        P_UPDATED_COUNT OUT NUMBER) IS
        V_SOURCE VARCHAR2(30) := NORMALIZE_SOURCE(P_SOURCE_TYPE);
    BEGIN
        VALIDATE_USER(P_USER_ID);
        -- Ignore concurrent inserts by another request for this same user.
        INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(T_NOTIFICATION_READ PK_T_NOTIFICATION_READ) */
        INTO T_NOTIFICATION_READ (NOTIFICATION_ID, USER_ID)
        SELECT ID, P_USER_ID FROM (
                    SELECT N.ID, N.TITLE, N.CONTENT, N.DATETIME, N.SOURCE_TYPE, N.SOURCE_KEY,
                           N.AI_RECIPIENT_ID, P_USER_ID USER_ID,
                           CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
                    FROM T_NOTIFICATION N
                    LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = P_USER_ID
                    WHERE (N.TARGET_TYPE = 0 OR EXISTS (SELECT 1 FROM T_NOTIFICATION_TARGET T
                               WHERE T.NOTIFICATION_ID = N.ID AND T.USER_ID = P_USER_ID))
                      AND (NVL(N.SOURCE_TYPE, '~') <> 'AI'
                           OR (N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, P_USER_ID) = 1))
                )
        WHERE USER_ID = P_USER_ID AND STATUS = 0 AND (V_SOURCE = 'ALL' OR SOURCE_TYPE = V_SOURCE);
        P_UPDATED_COUNT := SQL%ROWCOUNT;
    END;

    PROCEDURE RECONCILE_TARGETS IS
    BEGIN
        UPDATE T_NOTIFICATION SET TARGET_TYPE = 1 WHERE SOURCE_TYPE = 'AI' AND TARGET_TYPE <> 1;
        DELETE FROM T_NOTIFICATION_TARGET T
        WHERE EXISTS (SELECT 1 FROM T_NOTIFICATION N WHERE N.ID = T.NOTIFICATION_ID AND N.SOURCE_TYPE = 'AI')
          AND EXISTS (SELECT 1 FROM T_NOTIFICATION N WHERE N.ID = T.NOTIFICATION_ID
                      AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 0);
        INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(T_NOTIFICATION_TARGET PK_T_NOTIFICATION_TARGET) */
        INTO T_NOTIFICATION_TARGET (NOTIFICATION_ID, USER_ID)
        SELECT N.ID, U.USERID FROM T_NOTIFICATION N
        CROSS JOIN (SELECT DISTINCT USERID FROM T_USERS WHERE USERACTIVE = 1 AND USERID > 0) U
        WHERE N.SOURCE_TYPE = 'AI'
          AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, U.USERID) = 1
          AND NOT EXISTS (SELECT 1 FROM T_NOTIFICATION_TARGET T
                          WHERE T.NOTIFICATION_ID = N.ID AND T.USER_ID = U.USERID);
    END;
END AI_NOTIFICATION_PKG;
/

-- Preserve the old API signatures and commit behavior while closing stale AI
-- visibility through legacy callers. CREATE_NOTIFICATION remains local-only.
CREATE OR REPLACE PACKAGE BODY NOTIFICATION_PKG AS
    PROCEDURE GET_STATE(P_USER_ID IN NUMBER, P_OUT_CURSOR OUT T_CURSOR) IS
    BEGIN AI_NOTIFICATION_PKG.GET_STATE(P_USER_ID, P_OUT_CURSOR); END;

    PROCEDURE GET_PAGE(P_USER_ID IN NUMBER, P_STATUS IN NUMBER,
        P_PAGE_INDEX IN NUMBER, P_PAGE_SIZE IN NUMBER,
        P_DATA_CURSOR OUT T_CURSOR, P_TOTAL_CURSOR OUT T_CURSOR) IS
    BEGIN
        AI_NOTIFICATION_PKG.GET_PAGE(P_USER_ID, P_STATUS, P_PAGE_INDEX, P_PAGE_SIZE,
            'ALL', P_DATA_CURSOR, P_TOTAL_CURSOR);
    END;

    PROCEDURE MARK_READ(P_USER_ID IN NUMBER, P_ID IN NUMBER, P_UPDATED_COUNT OUT NUMBER) IS
    BEGIN AI_NOTIFICATION_PKG.MARK_READ(P_USER_ID, P_ID, P_UPDATED_COUNT); COMMIT; END;

    PROCEDURE MARK_ALL_READ(P_USER_ID IN NUMBER, P_UPDATED_COUNT OUT NUMBER) IS
    BEGIN AI_NOTIFICATION_PKG.MARK_ALL_READ(P_USER_ID, 'ALL', P_UPDATED_COUNT); COMMIT; END;

    PROCEDURE CREATE_NOTIFICATION(P_TITLE IN NVARCHAR2, P_CONTENT IN NVARCHAR2,
        P_USER_IDS IN VARCHAR2, P_ID OUT NUMBER) IS
        V_TARGET_TYPE NUMBER(1);
    BEGIN
        IF TRIM(P_TITLE) IS NULL OR TRIM(P_CONTENT) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20002, 'TITLE and CONTENT are required.');
        END IF;
        V_TARGET_TYPE := CASE WHEN TRIM(P_USER_IDS) IS NULL THEN 0 ELSE 1 END;
        INSERT INTO T_NOTIFICATION (TITLE, CONTENT, DATETIME, TARGET_TYPE)
        VALUES (TRIM(P_TITLE), TRIM(P_CONTENT), SYSTIMESTAMP, V_TARGET_TYPE) RETURNING ID INTO P_ID;
        IF V_TARGET_TYPE = 1 THEN
            INSERT INTO T_NOTIFICATION_TARGET (NOTIFICATION_ID, USER_ID)
            SELECT P_ID, USER_ID FROM (
                SELECT DISTINCT TO_NUMBER(TRIM(REGEXP_SUBSTR(P_USER_IDS, '[^,]+', 1, LEVEL))) USER_ID
                FROM DUAL CONNECT BY REGEXP_SUBSTR(P_USER_IDS, '[^,]+', 1, LEVEL) IS NOT NULL
            ) WHERE USER_ID > 0;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20003, 'At least one target USER_ID is required.');
            END IF;
        END IF;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;
END NOTIFICATION_PKG;
/

BEGIN
    AI_NOTIFICATION_PKG.RECONCILE_TARGETS;
    COMMIT;
END;
/

DECLARE
    V_INVALID NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_INVALID FROM USER_OBJECTS
    WHERE OBJECT_NAME IN ('AI_NOTIFICATION_PKG', 'NOTIFICATION_PKG') AND STATUS <> 'VALID';
    IF V_INVALID > 0 THEN RAISE_APPLICATION_ERROR(-20143, 'Notification integration has invalid packages. Inspect USER_ERRORS.'); END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_NOTIFICATION.AI_RECIPIENT_ID IS ''Original NL2SQL requester identity; not an ATFM user ID''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_NOTIFICATION.SOURCE_HASH IS ''Idempotency key: email hash or AI_QUERY:<notification id>''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE T_AI_RECIPIENT_MAP IS ''Explicit requester-to-active-ATFM-user grants. Any row suppresses automatic email matching.''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE T_AI_NOTIFICATION_SYNC IS ''Durable cursor and audience policy. ALL_USERS is the explicitly requested initial policy.''';
END;
/


