SET SERVEROUTPUT ON
SET LINESIZE 240
SET PAGESIZE 100

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'MESSAGE_FLIGHT_PKG'
ORDER BY OBJECT_TYPE;

SELECT TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME = 'MESSAGE_FLIGHT_PKG'
ORDER BY SEQUENCE;

VARIABLE flight_cursor REFCURSOR;
BEGIN
    MESSAGE_FLIGHT_PKG.GET_FLIGHTS_ON_MESSAGE(
        P_DATE       => '29-07-2026',
        P_MESS_TYPE  => 'HVN MESSAGE',
        P_THONG_BAO_MODE => 0,
        P_PART_NO    => 0,
        P_FROM_AIRP  => NULL,
        P_TO_AIRP    => NULL,
        P_OPER_ID    => NULL,
        P_PAGESIZE   => 5,
        P_PAGEINDEX  => 0,
        P_OUT_CURSOR => :flight_cursor
    );
END;
/
PRINT flight_cursor;

SELECT COUNT(*) AS EXCLUDED_THONG_BAO_MESSAGES
FROM T_PLAN_MESSAGE
WHERE TRUNC(FLIGHTDATE) = DATE '2026-07-29'
  AND MESS_TYPE = 'HVN MESSAGE'
  AND INSTR(UPPER(CONTENT), 'THONG BAO') > 0;
