SET PAGESIZE 200
SET LINESIZE 240
SET TRIMSPOOL ON

PROMPT === Column and current data lengths ===

SELECT COLUMN_NAME,
       DATA_TYPE,
       DATA_LENGTH,
       CHAR_LENGTH,
       CHAR_USED,
       NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'T_PERMMASTER_SC'
   AND COLUMN_NAME IN ('PERMNBR', 'PERMNBR_ID')
 ORDER BY COLUMN_ID;

SELECT COUNT(*) AS ROW_COUNT,
       MAX(LENGTH(PERMNBR)) AS MAX_PERMNBR_LENGTH,
       MAX(LENGTH(PERMNBR_ID)) AS MAX_PERMNBR_ID_LENGTH
  FROM T_PERMMASTER_SC;

PROMPT === Insert/update argument compatibility ===

SELECT PACKAGE_NAME,
       OBJECT_NAME,
       ARGUMENT_NAME,
       POSITION,
       DATA_TYPE,
       DATA_LENGTH,
       IN_OUT
  FROM USER_ARGUMENTS
 WHERE PACKAGE_NAME = 'PERM_PKG'
   AND OBJECT_NAME IN
       ('PERMMASTER_SC_INSERT', 'PERMMASTER_SC_UPDATE')
   AND ARGUMENT_NAME IN ('P_PERMNBR', 'P_PERMNBR_ID')
 ORDER BY OBJECT_NAME, POSITION;

PROMPT === Updated PERM_PKG predicates ===

SELECT TYPE, LINE, TRIM(TEXT) AS TEXT
  FROM USER_SOURCE
 WHERE NAME = 'PERM_PKG'
   AND TYPE = 'PACKAGE BODY'
   AND
   (
       LOWER(TEXT) LIKE '%upper(trim(permnbr)) like%'
       OR LOWER(TEXT) LIKE '%upper(trim(permnbr)) = upper(trim(p_flightnbr))%'
   )
 ORDER BY LINE;

PROMPT === Package errors and dependent object status ===

SELECT TYPE, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'PERM_PKG'
 ORDER BY TYPE, SEQUENCE;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           SELECT DISTINCT NAME
             FROM USER_SOURCE
            WHERE UPPER(TEXT) LIKE '%T_PERMMASTER_SC%'
       )
 ORDER BY STATUS, OBJECT_TYPE, OBJECT_NAME;
