-- Hoan tac phan mo rong nguon email cua T_NOTIFICATION.

DECLARE
    V_COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_NOTIFICATION'
      AND COLUMN_NAME = 'SOURCE_TYPE';

    IF V_COLUMN_COUNT > 0 THEN
        EXECUTE IMMEDIATE '
            DELETE FROM T_NOTIFICATION
            WHERE SOURCE_TYPE = ''EMAIL_API''';
        COMMIT;
    END IF;
END;
/

DECLARE
    V_INDEX_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_INDEX_COUNT
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UX_T_NOTIFICATION_SOURCE';

    IF V_INDEX_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX UX_T_NOTIFICATION_SOURCE';
    END IF;
END;
/

DECLARE
    V_COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_NOTIFICATION'
      AND COLUMN_NAME = 'SOURCE_KEY';

    IF V_COLUMN_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_NOTIFICATION DROP COLUMN SOURCE_KEY';
    END IF;
END;
/

DECLARE
    V_COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_NOTIFICATION'
      AND COLUMN_NAME = 'SOURCE_TYPE';

    IF V_COLUMN_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_NOTIFICATION DROP COLUMN SOURCE_TYPE';
    END IF;
END;
/
