DECLARE v_id NUMBER; BEGIN SELECT ID INTO v_id FROM T_MENUS WHERE LOWER(TRIM(MENUURL))=LOWER('ReportNew/KHBHDBNCompare.aspx'); DELETE FROM T_USERMENU WHERE MENU_ID=v_id; DELETE FROM T_MENUS WHERE ID=v_id; COMMIT; EXCEPTION WHEN NO_DATA_FOUND THEN NULL; END;
/
