-- Read metadata, then exercise isolated notification fixtures inside one
-- transaction that is ALWAYS rolled back. Do not call legacy commit wrappers.
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM USER_OBJECTS
    WHERE OBJECT_NAME IN ('T_AI_RECIPIENT_MAP', 'T_AI_NOTIFICATION_SYNC',
        'AI_NOTIFICATION_PKG', 'NOTIFICATION_PKG')
      AND STATUS = 'VALID';
    IF V_COUNT <> 6 THEN RAISE_APPLICATION_ERROR(-20147, 'Expected 6 valid notification integration objects.'); END IF;
    FOR R IN (SELECT NAME, TYPE, LINE, POSITION, TEXT FROM USER_ERRORS
              WHERE NAME IN ('AI_NOTIFICATION_PKG', 'NOTIFICATION_PKG')
              ORDER BY NAME, TYPE, SEQUENCE) LOOP
        DBMS_OUTPUT.PUT_LINE(R.NAME || ' ' || R.TYPE || ' ' || R.LINE || ':' || R.POSITION || ' ' || R.TEXT);
    END LOOP;
    FOR R IN (SELECT SOURCE_NAME, LAST_ID, AUDIENCE_MODE FROM T_AI_NOTIFICATION_SYNC) LOOP
        DBMS_OUTPUT.PUT_LINE(R.SOURCE_NAME || ': last_id=' || R.LAST_ID || ', audience=' || R.AUDIENCE_MODE);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('PASS 6 valid schema objects.');
END;
/

DECLARE
    V_USER1 NUMBER;
    V_USER2 NUMBER;
    V_ACTIVE_COUNT NUMBER;
    V_AI_ID NUMBER;
    V_LOCAL_ID NUMBER;
    V_UPDATED NUMBER;
    V_COUNT NUMBER;
    V_CASES NUMBER := 0;
    V_KEY VARCHAR2(32) := LOWER(RAWTOHEX(SYS_GUID()));
    V_EMAIL VARCHAR2(40);
    PROCEDURE ASSERT_TRUE(P_OK BOOLEAN, P_MESSAGE VARCHAR2) IS
    BEGIN
        IF P_OK IS NULL OR NOT P_OK THEN RAISE_APPLICATION_ERROR(-20149, P_MESSAGE); END IF;
        V_CASES := V_CASES + 1;
    END;
BEGIN
    SAVEPOINT AI_VERIFY_START;
    SELECT MIN(USERID), MAX(USERID), COUNT(DISTINCT USERID)
    INTO V_USER1, V_USER2, V_ACTIVE_COUNT FROM T_USERS WHERE USERACTIVE = 1 AND USERID > 0;
    IF V_ACTIVE_COUNT < 2 THEN RAISE_APPLICATION_ERROR(-20148, 'Verification needs two existing active users.'); END IF;
    V_EMAIL := SUBSTR(V_KEY, 1, 20) || '@example.test';

    UPDATE T_AI_NOTIFICATION_SYNC SET AUDIENCE_MODE = 'ALL_USERS' WHERE SOURCE_NAME = 'NL2SQL';
    INSERT INTO T_NOTIFICATION(TITLE, CONTENT, TARGET_TYPE, SOURCE_TYPE, SOURCE_KEY, SOURCE_HASH, AI_RECIPIENT_ID)
    VALUES ('AI integration verification', 'Temporary rollback-only fixture', 1,
        'AI_QUERY', V_KEY, 'AI_VERIFY:' || V_KEY, 'Guest-' || V_KEY) RETURNING ID INTO V_AI_ID;
    AI_NOTIFICATION_PKG.RECONCILE_TARGETS;
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = V_ACTIVE_COUNT, 'ALL_USERS must include all active accounts.');
    SELECT COUNT(*) INTO V_COUNT FROM T_NOTIFICATION_TARGET WHERE NOTIFICATION_ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = V_ACTIVE_COUNT, 'ALL_USERS must persist one target per active account.');

    AI_NOTIFICATION_PKG.MARK_READ(V_USER1, V_AI_ID, V_UPDATED);
    ASSERT_TRUE(V_UPDATED = 1, 'First user must be able to read the AI notification.');
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID AND USER_ID = V_USER2 AND STATUS = 0;
    ASSERT_TRUE(V_COUNT = 1, 'Reading must not change another user read state.');
    AI_NOTIFICATION_PKG.MARK_READ(V_USER1, V_AI_ID, V_UPDATED);
    ASSERT_TRUE(V_UPDATED = 0, 'Reading twice must be idempotent.');

    INSERT INTO T_NOTIFICATION(TITLE, CONTENT, TARGET_TYPE)
    VALUES ('Local integration verification', 'Must remain unread by AI-only mark-all', 1) RETURNING ID INTO V_LOCAL_ID;
    INSERT INTO T_NOTIFICATION_TARGET(NOTIFICATION_ID, USER_ID) VALUES(V_LOCAL_ID, V_USER2);
    AI_NOTIFICATION_PKG.MARK_ALL_READ(V_USER2, 'AI_QUERY', V_UPDATED);
    SELECT COUNT(*) INTO V_COUNT FROM T_NOTIFICATION_READ WHERE NOTIFICATION_ID = V_LOCAL_ID AND USER_ID = V_USER2;
    ASSERT_TRUE(V_COUNT = 0, 'AI-only mark-all must leave local notifications unread.');
    SELECT COUNT(*) INTO V_COUNT FROM T_NOTIFICATION_READ WHERE NOTIFICATION_ID = V_AI_ID AND USER_ID = V_USER2;
    ASSERT_TRUE(V_COUNT = 1, 'AI-only mark-all must mark the AI fixture read.');

    UPDATE T_AI_NOTIFICATION_SYNC SET AUDIENCE_MODE = 'MAPPED' WHERE SOURCE_NAME = 'NL2SQL';
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 0, 'Switching to MAPPED must hide unknown guests before reconciliation.');
    INSERT INTO T_AI_RECIPIENT_MAP(RECIPIENT_ID, USER_ID) VALUES('Guest-' || V_KEY, V_USER1);
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID AND USER_ID = V_USER1;
    ASSERT_TRUE(V_COUNT = 1, 'Explicit guest mapping must grant its selected active user.');
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID AND USER_ID = V_USER2;
    ASSERT_TRUE(V_COUNT = 0, 'Explicit mapping must not grant other users.');
    UPDATE T_NOTIFICATION SET AI_RECIPIENT_ID = 'guest-' || V_KEY WHERE ID = V_AI_ID;
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 0, 'Guest identifiers must remain case-sensitive.');

    UPDATE T_USERS SET USEREMAIL = V_EMAIL WHERE USERID = V_USER1;
    UPDATE T_NOTIFICATION SET AI_RECIPIENT_ID = UPPER(V_EMAIL) WHERE ID = V_AI_ID;
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID NOTIFICATION_ID, U.USERID USER_ID
        FROM T_NOTIFICATION N CROSS JOIN (SELECT DISTINCT USERID FROM T_USERS WHERE USERACTIVE = 1 AND USERID > 0) U
        WHERE N.SOURCE_TYPE = 'AI_QUERY' AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, U.USERID) = 1) WHERE NOTIFICATION_ID = V_AI_ID AND USER_ID = V_USER1;
    ASSERT_TRUE(V_COUNT = 1, 'Unique active email must match without case sensitivity.');
    UPDATE T_USERS SET USEREMAIL = V_EMAIL WHERE USERID = V_USER2;
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID NOTIFICATION_ID, U.USERID USER_ID
        FROM T_NOTIFICATION N CROSS JOIN (SELECT DISTINCT USERID FROM T_USERS WHERE USERACTIVE = 1 AND USERID > 0) U
        WHERE N.SOURCE_TYPE = 'AI_QUERY' AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, U.USERID) = 1) WHERE NOTIFICATION_ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 0, 'Duplicate active email must not select either account automatically.');
    INSERT INTO T_AI_RECIPIENT_MAP(RECIPIENT_ID, USER_ID, IS_ACTIVE) VALUES(V_EMAIL, V_USER1, 1);
    AI_NOTIFICATION_PKG.RECONCILE_TARGETS;
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 1, 'Explicit mapping must resolve an ambiguous email.');
    UPDATE T_AI_RECIPIENT_MAP SET IS_ACTIVE = 0 WHERE RECIPIENT_ID = V_EMAIL;
    UPDATE T_USERS SET USEREMAIL = NULL WHERE USERID = V_USER2;
    SELECT COUNT(*) INTO V_COUNT FROM (SELECT N.ID, T.USER_ID,
        CASE WHEN R.NOTIFICATION_ID IS NULL THEN 0 ELSE 1 END STATUS
        FROM T_NOTIFICATION N JOIN T_NOTIFICATION_TARGET T ON T.NOTIFICATION_ID = N.ID
        LEFT JOIN T_NOTIFICATION_READ R ON R.NOTIFICATION_ID = N.ID AND R.USER_ID = T.USER_ID
        WHERE N.TARGET_TYPE = 1 AND AI_NOTIFICATION_PKG.CAN_RECEIVE(N.AI_RECIPIENT_ID, T.USER_ID) = 1) WHERE ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 0, 'Inactive explicit mapping must suppress automatic email fallback.');
    AI_NOTIFICATION_PKG.RECONCILE_TARGETS;
    SELECT COUNT(*) INTO V_COUNT FROM T_NOTIFICATION_TARGET WHERE NOTIFICATION_ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 0, 'Reconciliation must remove revoked targets.');
    SELECT COUNT(*) INTO V_COUNT FROM T_NOTIFICATION_READ WHERE NOTIFICATION_ID = V_AI_ID;
    ASSERT_TRUE(V_COUNT = 2, 'Reconciliation must preserve independent read history.');

    ROLLBACK TO AI_VERIFY_START;
    DBMS_OUTPUT.PUT_LINE('PASS ' || V_CASES || ' notification integration assertions; all fixture changes rolled back.');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK TO AI_VERIFY_START;
    RAISE;
END;
/
