-- Rollback ISACCEPTED cho T_FINISHED_FLIGHTS.
-- Cảnh báo: thao tác này xóa trạng thái Accepted đã lưu.

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE FINISHED_STATUS_PKG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IX_TFIN_ACCEPTED_DATE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1418 THEN
            RAISE;
        END IF;
END;
/

DECLARE
    v_count PLS_INTEGER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'T_FINISHED_FLIGHTS'
       AND COLUMN_NAME = 'ISACCEPTED';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE T_FINISHED_FLIGHTS DROP COLUMN ISACCEPTED';
    END IF;
END;
/
