-- ============================================================================
-- Verify: kiem tra ADSB_PERFORMANCE_PKG sau khi deploy.
-- Chi doc, khong thay doi du lieu.
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF

DECLARE
    V_COUNT PLS_INTEGER;
BEGIN
    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'ADSB_PERFORMANCE_PKG'
       AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
       AND STATUS = 'VALID';

    IF V_COUNT <> 2 THEN
        RAISE_APPLICATION_ERROR(-20976, 'ADSB_PERFORMANCE_PKG khong VALID');
    END IF;

    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_ERRORS
     WHERE NAME = 'ADSB_PERFORMANCE_PKG';

    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20977,
            'ADSB_PERFORMANCE_PKG con ' || V_COUNT || ' loi bien dich'
        );
    END IF;

    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_ARGUMENTS
     WHERE PACKAGE_NAME = 'ADSB_PERFORMANCE_PKG'
       AND OBJECT_NAME = 'GET_LOGS'
       AND ARGUMENT_NAME IN
           ('P_FROM_DATE', 'P_TO_DATE', 'P_PERM_TYPE', 'P_OPER', 'P_OUT_CURSOR');

    IF V_COUNT <> 5 THEN
        RAISE_APPLICATION_ERROR(-20978, 'Sai chu ky ADSB_PERFORMANCE_PKG.GET_LOGS');
    END IF;

    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_ARGUMENTS
     WHERE PACKAGE_NAME = 'ADSB_PERFORMANCE_PKG'
       AND OBJECT_NAME = 'GET_OPERATORS'
       AND ARGUMENT_NAME IN
           ('P_FROM_DATE', 'P_TO_DATE', 'P_PERM_TYPE', 'P_OUT_CURSOR');

    IF V_COUNT <> 4 THEN
        RAISE_APPLICATION_ERROR(-20979, 'Sai chu ky ADSB_PERFORMANCE_PKG.GET_OPERATORS');
    END IF;

    DBMS_OUTPUT.PUT_LINE('ADSB_PERFORMANCE_PKG verify: OK');
END;
/

-- Chay thu GET_LOGS voi khoang 7 ngay gan nhat (chi doc).
DECLARE
    V_CURSOR ADSB_PERFORMANCE_PKG.T_CURSOR;
    V_ROWS   PLS_INTEGER := 0;
    V_ID     NUMBER;
    V_CALLSIGN VARCHAR2(400);
    V_FROM_AIRP VARCHAR2(400);
    V_TO_AIRP VARCHAR2(400);
    V_ETD VARCHAR2(400);
    V_ETA VARCHAR2(400);
    V_STATUS NUMBER;
    V_UPDATED VARCHAR2(400);
    V_TIME_IN VARCHAR2(400);
    V_TIME_OUT VARCHAR2(400);
    V_PERMTYPE VARCHAR2(400);
    V_LOG_DATE DATE;
    V_OPER VARCHAR2(400);
BEGIN
    ADSB_PERFORMANCE_PKG.GET_LOGS
    (
        P_FROM_DATE  => TO_CHAR(SYSDATE - 7, 'DD-MM-YYYY'),
        P_TO_DATE    => TO_CHAR(SYSDATE, 'DD-MM-YYYY'),
        P_PERM_TYPE  => 'ALL',
        P_OPER       => NULL,
        P_OUT_CURSOR => V_CURSOR
    );

    LOOP
        FETCH V_CURSOR INTO
            V_ID, V_CALLSIGN, V_FROM_AIRP, V_TO_AIRP, V_ETD, V_ETA,
            V_STATUS, V_UPDATED, V_TIME_IN, V_TIME_OUT, V_PERMTYPE,
            V_LOG_DATE, V_OPER;
        EXIT WHEN V_CURSOR%NOTFOUND;
        V_ROWS := V_ROWS + 1;
    END LOOP;
    CLOSE V_CURSOR;

    DBMS_OUTPUT.PUT_LINE('GET_LOGS 7 ngay gan nhat: ' || V_ROWS || ' dong');
END;
/

-- Chay thu GET_OPERATORS voi khoang 7 ngay gan nhat (chi doc).
DECLARE
    V_CURSOR ADSB_PERFORMANCE_PKG.T_CURSOR;
    V_ROWS   PLS_INTEGER := 0;
    V_OPER   VARCHAR2(400);
BEGIN
    ADSB_PERFORMANCE_PKG.GET_OPERATORS
    (
        P_FROM_DATE  => TO_CHAR(SYSDATE - 7, 'DD-MM-YYYY'),
        P_TO_DATE    => TO_CHAR(SYSDATE, 'DD-MM-YYYY'),
        P_PERM_TYPE  => NULL,
        P_OUT_CURSOR => V_CURSOR
    );

    LOOP
        FETCH V_CURSOR INTO V_OPER;
        EXIT WHEN V_CURSOR%NOTFOUND;
        V_ROWS := V_ROWS + 1;
    END LOOP;
    CLOSE V_CURSOR;

    DBMS_OUTPUT.PUT_LINE('GET_OPERATORS 7 ngay gan nhat: ' || V_ROWS || ' hang khai thac');
END;
/

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'ADSB_PERFORMANCE_PKG'
 ORDER BY OBJECT_TYPE;

SELECT POSITION, ARGUMENT_NAME, IN_OUT, DATA_TYPE
  FROM USER_ARGUMENTS
 WHERE PACKAGE_NAME = 'ADSB_PERFORMANCE_PKG'
 ORDER BY OBJECT_NAME, SEQUENCE;
