DECLARE v_menu NUMBER; v_user NUMBER; v_parent NUMBER; BEGIN
 SELECT USERID INTO v_user FROM T_USERS WHERE LOWER(TRIM(USERNAME))='admin' AND ROWNUM=1;
 SELECT ID INTO v_parent FROM T_MENUS WHERE UPPER(MENUNAME) LIKE '%FLIGHTS PLAN%' AND ROWNUM=1;
 BEGIN SELECT ID INTO v_menu FROM T_MENUS WHERE LOWER(TRIM(MENUURL))=LOWER('ReportNew/KHBHDBNCompare.aspx') AND ROWNUM=1;
 UPDATE T_MENUS SET MENUNAME='Đánh giá, so sánh KHBHĐBN',PARRENTID=v_parent,ISDISPLAY=1,DATEMODIFY=SYSDATE,USERMODIFY=v_user WHERE ID=v_menu;
 EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO T_MENUS(ID,MENUNAME,MENUDESC,MENUORDER,PARRENTID,DATECREATED,DATEMODIFY,MENUURL,USERCREATE,USERMODIFY,ISDISPLAY) VALUES(NULL,'Đánh giá, so sánh KHBHĐBN','So sánh KHBHĐBN giữa hai ngày',90,v_parent,SYSDATE,SYSDATE,'ReportNew/KHBHDBNCompare.aspx',v_user,v_user,1) RETURNING ID INTO v_menu; END;
 MERGE INTO T_USERMENU u USING (SELECT v_user uid,v_menu mid FROM dual) s ON (u.USER_ID=s.uid AND u.MENU_ID=s.mid AND NVL(u.GROUP_ID,0)=0) WHEN MATCHED THEN UPDATE SET R_ADD=1,R_EDIT=1,R_DEL=1,R_PUB=1,DATEMODIFY=SYSDATE WHEN NOT MATCHED THEN INSERT(ID,USER_ID,MENU_ID,R_ADD,R_EDIT,R_DEL,R_PUB,DATECREATED,DATEMODIFY,GROUP_ID) VALUES(NULL,s.uid,s.mid,1,1,1,1,SYSDATE,SYSDATE,0); COMMIT; END;
/
