SET LONG 10000;
SET LINESIZE 240;
SET PAGESIZE 200;

PROMPT === CHANGE_DETAIL column ===

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'T_DAYFLIGHTS_ACTION_HISTORY'
   AND COLUMN_NAME = 'CHANGE_DETAIL';

PROMPT === Trigger and package status ===

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           'TRG_TDF_GOINGON_ACTION_HIS',
           'DAYFLIGHT_HISTORY_PKG'
       )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT NAME, TYPE, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME IN
       (
           'TRG_TDF_GOINGON_ACTION_HIS',
           'DAYFLIGHT_HISTORY_PKG'
       )
 ORDER BY NAME, TYPE, SEQUENCE;

PROMPT === Recent action details ===

SELECT *
  FROM
  (
      SELECT HISTORY_ID,
             FLIGHT_ID,
             ACTION_TYPE,
             CALLSIGN,
             ACTION_USER,
             DBMS_LOB.SUBSTR(CHANGE_DETAIL, 4000, 1) CHANGE_DETAIL,
             ACTION_DATE
        FROM T_DAYFLIGHTS_ACTION_HISTORY
       ORDER BY HISTORY_ID DESC
  )
 WHERE ROWNUM <= 20;
