SELECT m.ID, m.MENUNAME, m.MENUURL, m.PARRENTID, m.ISDISPLAY,
       u.USERNAME, um.R_ADD, um.R_EDIT, um.R_PUB
  FROM T_MENUS m
  LEFT JOIN T_USERMENU um ON um.MENU_ID = m.ID
  LEFT JOIN T_USERS u ON u.USERID = um.USER_ID
 WHERE LOWER(TRIM(m.MENUURL)) = LOWER('MessManagement/LiveFireMessage.aspx')
 ORDER BY u.USERNAME;
