SET SERVEROUTPUT ON;

PROMPT === Objects ===

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           'T_DAYFLIGHTS_ACTION_HISTORY',
           'SEQ_T_DAYFLIGHTS_ACTION_HIS',
           'TRG_TDF_GOINGON_ACTION_HIS',
           'IX_TDF_ACTION_HIS_FLIGHT',
           'IX_TDF_ACTION_HIS_SEARCH'
       )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT === Trigger ===

SELECT TRIGGER_NAME, STATUS, TRIGGERING_EVENT
  FROM USER_TRIGGERS
 WHERE TRIGGER_NAME = 'TRG_TDF_GOINGON_ACTION_HIS';

PROMPT === Columns ===

SELECT COLUMN_ID,
       COLUMN_NAME,
       DATA_TYPE,
       DATA_LENGTH,
       NULLABLE,
       DATA_DEFAULT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'T_DAYFLIGHTS_ACTION_HISTORY'
 ORDER BY COLUMN_ID;

PROMPT === Index columns ===

SELECT INDEX_NAME, COLUMN_POSITION, COLUMN_NAME
  FROM USER_IND_COLUMNS
 WHERE TABLE_NAME = 'T_DAYFLIGHTS_ACTION_HISTORY'
 ORDER BY INDEX_NAME, COLUMN_POSITION;

PROMPT === Recent history ===

SELECT *
  FROM
  (
      SELECT HISTORY_ID,
             SOURCE_ROW_ID,
             FLIGHT_ID,
             ACTION_TYPE,
             CALLSIGN,
             FLIGHTDATE,
             ACTION_USER,
             ACTION_DATE
        FROM T_DAYFLIGHTS_ACTION_HISTORY
       ORDER BY HISTORY_ID DESC
  )
 WHERE ROWNUM <= 20;
