-- Rollback package/index rieng cua Cancel Permission SC V2.

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE PERM_IMP_V2_PKG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -4043 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IX_TSDF_CANCEL_MATCH_V2';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -1418 THEN RAISE; END IF;
END;
/
