-- Rollback phân tách trạng thái Accepted của T_CANCELED_FLIGHTS.

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE CANCELED_STATUS_PKG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE T_CANCELED_FLIGHTS '
        || 'DROP CONSTRAINT CK_TCAN_ISACCEPTED';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IX_TCAN_STATUS_DATE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE T_CANCELED_FLIGHTS DROP COLUMN ISACCEPTED';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/
