-- Bo sung khoa nguon de dong bo thong bao email tu VATM AeroSync API.
-- Chay script nay truoc khi deploy ma Notification.ashx.cs moi.

DECLARE
    V_COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_NOTIFICATION'
      AND COLUMN_NAME = 'SOURCE_TYPE';

    IF V_COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE T_NOTIFICATION
            ADD SOURCE_TYPE VARCHAR2(30 CHAR) NULL';
    END IF;
END;
/

DECLARE
    V_COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_NOTIFICATION'
      AND COLUMN_NAME = 'SOURCE_KEY';

    IF V_COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE T_NOTIFICATION
            ADD SOURCE_KEY VARCHAR2(80 CHAR) NULL';
    END IF;
END;
/

DECLARE
    V_INDEX_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_INDEX_COUNT
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UX_T_NOTIFICATION_SOURCE';

    IF V_INDEX_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE UNIQUE INDEX UX_T_NOTIFICATION_SOURCE
            ON T_NOTIFICATION (SOURCE_TYPE, SOURCE_KEY)';
    END IF;
END;
/

COMMENT ON COLUMN T_NOTIFICATION.SOURCE_TYPE IS
    'Loai nguon ngoai tao thong bao, vi du EMAIL_API';
COMMENT ON COLUMN T_NOTIFICATION.SOURCE_KEY IS
    'Khoa bam duy nhat cua ban ghi nguon, dung de dong bo khong trung lap';
