-- Chi rollback object staging V2. Khong cham vao T_PERMSC_IMP.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_PERMSC_CANCEL_V2 PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_T_PERMSC_CANCEL_V2';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -2289 THEN RAISE; END IF;
END;
/
