-- Hoan tac viec tach SOURCE_HASH va tra SOURCE_TYPE/SOURCE_KEY ve dang cu.

-- Tra lai khoa dedupe vao SOURCE_KEY va nhan EMAIL_API vao SOURCE_TYPE.
UPDATE T_NOTIFICATION
SET SOURCE_TYPE = 'EMAIL_API',
    SOURCE_KEY = SOURCE_HASH
WHERE SOURCE_HASH IS NOT NULL;

COMMIT;

DECLARE
    V_INDEX_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_INDEX_COUNT
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UX_T_NOTIFICATION_SOURCE_HASH';

    IF V_INDEX_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX UX_T_NOTIFICATION_SOURCE_HASH';
    END IF;
END;
/

DECLARE
    V_INDEX_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_INDEX_COUNT
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UX_T_NOTIFICATION_SOURCE';

    IF V_INDEX_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE UNIQUE INDEX UX_T_NOTIFICATION_SOURCE
            ON T_NOTIFICATION (SOURCE_TYPE, SOURCE_KEY)';
    END IF;
END;
/

DECLARE
    V_COLUMN_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'T_NOTIFICATION'
      AND COLUMN_NAME = 'SOURCE_HASH';

    IF V_COLUMN_COUNT > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE T_NOTIFICATION DROP COLUMN SOURCE_HASH';
    END IF;
END;
/

COMMENT ON COLUMN T_NOTIFICATION.SOURCE_TYPE IS
    'Loai nguon ngoai tao thong bao, vi du EMAIL_API';
COMMENT ON COLUMN T_NOTIFICATION.SOURCE_KEY IS
    'Khoa bam duy nhat cua ban ghi nguon, dung de dong bo khong trung lap';
