SET SERVEROUTPUT ON
SET LINESIZE 240
SET PAGESIZE 100

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'AMHS_OUTBOX_PKG'
ORDER BY OBJECT_TYPE;

SELECT TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME = 'AMHS_OUTBOX_PKG'
ORDER BY SEQUENCE;

SELECT INDEX_NAME, STATUS, VISIBILITY
FROM USER_INDEXES
WHERE INDEX_NAME IN
(
    'IX_OUTBOX_ORACLE_TIME',
    'IX_OUTBOX_ADDR_OUTBOX_ID'
)
ORDER BY INDEX_NAME;

VARIABLE outbox_cursor REFCURSOR;
BEGIN
    AMHS_OUTBOX_PKG.GET_OUTBOX_MESSAGES(
        P_FROM_DATE  => TO_CHAR(SYSDATE, 'DD-MM-YYYY'),
        P_TO_DATE    => TO_CHAR(SYSDATE, 'DD-MM-YYYY'),
        P_CONTENT    => NULL,
        P_PAGESIZE   => 10,
        P_PAGEINDEX  => 0,
        P_OUT_CURSOR => :outbox_cursor
    );
END;
/
PRINT outbox_cursor;
