SET SERVEROUTPUT ON
SET LINESIZE 220
SET PAGESIZE 100

PROMPT === COLUMN / STATUS COUNTS ===
SELECT COLUMN_NAME, DATA_TYPE, DATA_DEFAULT, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'T_CANCELED_FLIGHTS'
   AND COLUMN_NAME = 'ISACCEPTED';

SELECT ISACCEPTED, COUNT(*) AS ROW_COUNT
  FROM T_CANCELED_FLIGHTS
 GROUP BY ISACCEPTED
 ORDER BY ISACCEPTED;

PROMPT === INDEX / PACKAGE STATUS ===
SELECT INDEX_NAME, STATUS, VISIBILITY
  FROM USER_INDEXES
 WHERE TABLE_NAME = 'T_CANCELED_FLIGHTS'
   AND INDEX_NAME = 'IX_TCAN_STATUS_DATE';

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           'CANCELED_STATUS_PKG',
           'CANCEL_FLIGHTS_PKG',
           'FINISH_FLIGHTS_PKG'
       )
 ORDER BY OBJECT_NAME, OBJECT_TYPE;

SELECT TYPE, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME IN
       (
           'CANCELED_STATUS_PKG',
           'CANCEL_FLIGHTS_PKG',
           'FINISH_FLIGHTS_PKG'
       )
 ORDER BY NAME, SEQUENCE;

PROMPT === STATUS 1 SAMPLE ===
VARIABLE accepted_cursor REFCURSOR;
BEGIN
    CANCELED_STATUS_PKG.GET_CANCELED_FLIGHTS(
        P_PAGESIZE     => 2,
        P_PAGEINDEX    => 0,
        P_STARTDATE    => '01-07-2026',
        P_FINISHDATE   => '12-07-2026',
        P_ISACCEPTED   => 1,
        P_OUT_CURSOR   => :accepted_cursor
    );
END;
/
PRINT accepted_cursor;

PROMPT === STATUS 0 SAMPLE ===
VARIABLE pending_cursor REFCURSOR;
BEGIN
    CANCELED_STATUS_PKG.GET_CANCELED_FLIGHTS(
        P_PAGESIZE     => 2,
        P_PAGEINDEX    => 0,
        P_STARTDATE    => '01-07-2026',
        P_FINISHDATE   => '12-07-2026',
        P_ISACCEPTED   => 0,
        P_OUT_CURSOR   => :pending_cursor
    );
END;
/
PRINT pending_cursor;

PROMPT === ACCEPT NONEXISTENT ID (EXPECTED 0) ===
DECLARE
    v_missing_id NUMBER;
    v_returncode NUMBER;
BEGIN
    SELECT NVL(MAX(FLIGHT_ID), 0) + 1000000
      INTO v_missing_id
      FROM T_CANCELED_FLIGHTS;

    CANCELED_STATUS_PKG.ACCEPT_CANCELED_FLIGHTS(
        P_FLIGHT_IDS => TO_CHAR(v_missing_id),
        P_USER       => 'CODEX_VERIFY',
        P_RETURNCODE => v_returncode
    );

    DBMS_OUTPUT.PUT_LINE('P_RETURNCODE=' || TO_CHAR(v_returncode));
END;
/
