SET SERVEROUTPUT ON
SET LINESIZE 240
SET PAGESIZE 100

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'AMHS_OUTBOX_PKG'
ORDER BY OBJECT_TYPE;

SELECT TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME = 'AMHS_OUTBOX_PKG'
ORDER BY SEQUENCE;

SELECT INDEX_NAME, STATUS, VISIBILITY
FROM USER_INDEXES
WHERE INDEX_NAME IN
(
    'IX_OUTBOX_ORACLE_TIME',
    'IX_OUTBOX_ADDR_OUTBOX_ID'
)
ORDER BY INDEX_NAME;

VARIABLE outbox_cursor REFCURSOR;
BEGIN
    AMHS_OUTBOX_PKG.GET_OUTBOX_MESSAGES(
        P_FROM_DATE  => TO_CHAR(SYSDATE, 'DD-MM-YYYY'),
        P_TO_DATE    => TO_CHAR(SYSDATE, 'DD-MM-YYYY'),
        P_CONTENT    => NULL,
        P_PAGESIZE   => 10,
        P_PAGEINDEX  => 0,
        P_OUT_CURSOR => :outbox_cursor
    );
END;
/
PRINT outbox_cursor;

VARIABLE address_cursor REFCURSOR;
DECLARE
    v_outbox_id OUTBOX_ORACLE.ID%TYPE;
BEGIN
    SELECT MAX(ID)
    INTO v_outbox_id
    FROM OUTBOX_ORACLE;

    IF v_outbox_id IS NOT NULL THEN
        AMHS_OUTBOX_PKG.GET_OUTBOX_ADDRESSES(
            P_OUTBOX_ID  => v_outbox_id,
            P_OUT_CURSOR => :address_cursor
        );
    END IF;
END;
/
PRINT address_cursor;
