-- Canh bao: rollback se xoa toan bo lich su da ghi trong bang moi.

SET SERVEROUTPUT ON;

DECLARE
    l_count PLS_INTEGER;
BEGIN
    SELECT COUNT(*)
      INTO l_count
      FROM USER_TRIGGERS
     WHERE TRIGGER_NAME = 'TRG_TDF_GOINGON_ACTION_HIS';

    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TDF_GOINGON_ACTION_HIS';
    END IF;

    SELECT COUNT(*)
      INTO l_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'T_DAYFLIGHTS_ACTION_HISTORY';

    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE T_DAYFLIGHTS_ACTION_HISTORY PURGE';
    END IF;

    SELECT COUNT(*)
      INTO l_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = 'SEQ_T_DAYFLIGHTS_ACTION_HIS';

    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_T_DAYFLIGHTS_ACTION_HIS';
    END IF;
END;
/

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           'T_DAYFLIGHTS_ACTION_HISTORY',
           'SEQ_T_DAYFLIGHTS_ACTION_HIS',
           'TRG_TDF_GOINGON_ACTION_HIS'
       );
