-- Chỉ chạy khi cần gỡ toàn bộ phân hệ Airspace.
-- Dữ liệu trong T_FINISHFLIGHTS_AIRSPACE sẽ bị xóa vĩnh viễn.

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE AIRSPACE_PKG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FINISHFLIGHTS_AIRSPACE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_FINISHFLIGHTS_AIRSPACE CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE <> -942 THEN
            RAISE;
        END IF;
END;
/
