-- API tra cuu lich su them/cap nhat chuyen bay cho popup Flight extension.

CREATE OR REPLACE PACKAGE DAYFLIGHT_HISTORY_PKG AS
    TYPE T_CURSOR IS REF CURSOR;

    PROCEDURE GET_BY_FLIGHT_ID
    (
        P_FLIGHT_ID IN T_DAYFLIGHTS_ACTION_HISTORY.FLIGHT_ID%TYPE,
        P_OUT_CURSOR OUT T_CURSOR
    );
END DAYFLIGHT_HISTORY_PKG;
/

CREATE OR REPLACE PACKAGE BODY DAYFLIGHT_HISTORY_PKG AS
    PROCEDURE GET_BY_FLIGHT_ID
    (
        P_FLIGHT_ID IN T_DAYFLIGHTS_ACTION_HISTORY.FLIGHT_ID%TYPE,
        P_OUT_CURSOR OUT T_CURSOR
    )
    IS
    BEGIN
        OPEN P_OUT_CURSOR FOR
            SELECT HISTORY_ID,
                   SOURCE_ROW_ID,
                   FLIGHT_ID,
                   ACTION_TYPE,
                   CALLSIGN,
                   TO_CHAR(FLIGHTDATE, 'DD-MM-YYYY') AS FLIGHTDATE,
                   ACTION_USER,
                   TO_CHAR(
                       ACTION_DATE,
                       'DD-MM-YYYY HH24:MI:SS'
                   ) AS ACTION_DATE
              FROM T_DAYFLIGHTS_ACTION_HISTORY
             WHERE FLIGHT_ID = P_FLIGHT_ID
             ORDER BY HISTORY_ID DESC;
    END GET_BY_FLIGHT_ID;
END DAYFLIGHT_HISTORY_PKG;
/

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'DAYFLIGHT_HISTORY_PKG'
 ORDER BY OBJECT_TYPE;
