-- Verify API package va du lieu mau PERM_ID=203085.

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'PERMDETAIL_SC_HISTORY_PKG'
 ORDER BY OBJECT_TYPE;

SELECT LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'PERMDETAIL_SC_HISTORY_PKG'
 ORDER BY SEQUENCE;

VARIABLE V_CURSOR REFCURSOR;

BEGIN
    PERMDETAIL_SC_HISTORY_PKG.GET_BY_PERM_ID
    (
        P_PERM_ID    => 203085,
        P_OUT_CURSOR => :V_CURSOR
    );
END;
/

PRINT V_CURSOR;
