DECLARE v_menu NUMBER; v_user NUMBER; v_parent NUMBER; BEGIN
 SELECT USERID INTO v_user FROM T_USERS WHERE LOWER(TRIM(USERNAME))='admin' AND ROWNUM=1;
 SELECT ID INTO v_parent FROM T_MENUS WHERE UPPER(MENUNAME) LIKE '%FLIGHTS PLAN%' AND ROWNUM=1;
 BEGIN SELECT ID INTO v_menu FROM T_MENUS WHERE LOWER(TRIM(MENUURL))=LOWER('ReportNew/KHBHDBNCompare.aspx') AND ROWNUM=1;
 UPDATE T_MENUS SET MENUNAME='Đánh giá, so sánh KHBHĐBN',PARRENTID=v_parent,ISDISPLAY=1,DATEMODIFY=SYSDATE,USERMODIFY=v_user WHERE ID=v_menu;
 EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO T_MENUS(ID,MENUNAME,MENUDESC,MENUORDER,PARRENTID,DATECREATED,DATEMODIFY,MENUURL,USERCREATE,USERMODIFY,ISDISPLAY) VALUES(NULL,'Đánh giá, so sánh KHBHĐBN','So sánh KHBHĐBN giữa hai ngày',90,v_parent,SYSDATE,SYSDATE,'ReportNew/KHBHDBNCompare.aspx',v_user,v_user,1) RETURNING ID INTO v_menu; END;
 UPDATE T_USERMENU SET R_ADD=1,R_EDIT=1,R_DEL=1,R_PUB=1,DATEMODIFY=SYSDATE WHERE USER_ID=v_user AND MENU_ID=v_menu AND NVL(GROUP_ID,0)=0;
 IF SQL%ROWCOUNT=0 THEN INSERT INTO T_USERMENU(ID,USER_ID,MENU_ID,R_ADD,R_EDIT,R_DEL,R_PUB,DATECREATED,DATEMODIFY,GROUP_ID) VALUES(NULL,v_user,v_menu,1,1,1,1,SYSDATE,SYSDATE,0); END IF;
 COMMIT; END;
/
