SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'DAYFLIGHT_HISTORY_PKG'
 ORDER BY OBJECT_TYPE;

SELECT LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'DAYFLIGHT_HISTORY_PKG'
 ORDER BY TYPE, SEQUENCE;

VARIABLE P_OUT_CURSOR REFCURSOR;

BEGIN
    DAYFLIGHT_HISTORY_PKG.GET_BY_FLIGHT_ID
    (
        P_FLIGHT_ID => NULL,
        P_OUT_CURSOR => :P_OUT_CURSOR
    );
END;
/

PRINT P_OUT_CURSOR;
