-- Verify lich su thay doi chi tiet phep bay NO.

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           'T_PERMDETAIL_NO_ACTION_HISTORY',
           'SEQ_T_PERMDETAIL_NO_ACT_HIS',
           'TRG_T_PERMDETAIL_NO_ACTION_HIS'
       )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, DESCEND
  FROM USER_IND_COLUMNS
 WHERE TABLE_NAME = 'T_PERMDETAIL_NO_ACTION_HISTORY'
 ORDER BY INDEX_NAME, COLUMN_POSITION;

SELECT LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'TRG_T_PERMDETAIL_NO_ACTION_HIS'
 ORDER BY SEQUENCE;
