-- Rollback phan he dien van ban dan that.
-- Chu y: xoa ca du lieu chua phat trong T_PLAN_MESSAGE cua phan he nay.
BEGIN
    DELETE FROM T_PLAN_MESSAGE
     WHERE STATUS = 0
       AND MESS_TYPE = 'LIVE FIRE MESSAGE';
    COMMIT;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE LIVE_FIRE_MESSAGE_PKG';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -4043 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_LIVE_FIRE_MESSAGE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_T_LIVE_FIRE_MESSAGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -2289 THEN RAISE; END IF;
END;
/
