-- Verify API package va lich su chi tiet phep bay NO.

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME = 'PERMDETAIL_NO_HISTORY_PKG'
 ORDER BY OBJECT_TYPE;

SELECT LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'PERMDETAIL_NO_HISTORY_PKG'
 ORDER BY SEQUENCE;

SELECT PERM_ID, COUNT(*) AS HISTORY_COUNT
  FROM T_PERMDETAIL_NO_ACTION_HISTORY
 GROUP BY PERM_ID
 ORDER BY HISTORY_COUNT DESC, PERM_ID;
