-- Verify lich su thay doi chi tiet phep bay SC.

SET SERVEROUTPUT ON;

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN
       (
           'T_PERMDETAIL_SC_ACTION_HISTORY',
           'SEQ_T_PERMDETAIL_SC_ACT_HIS',
           'TRG_T_PERMDETAIL_SC_ACTION_HIS'
       )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, DESCEND
  FROM USER_IND_COLUMNS
 WHERE TABLE_NAME = 'T_PERMDETAIL_SC_ACTION_HISTORY'
 ORDER BY INDEX_NAME, COLUMN_POSITION;

SELECT LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'TRG_T_PERMDETAIL_SC_ACTION_HIS'
 ORDER BY SEQUENCE;

-- Mau tra cuu lich su cua mot phep bay:
-- SELECT HISTORY_ID,
--        PERM_DETAIL_ID,
--        FLIGHT_PK,
--        PERM_ID,
--        ACTION_TYPE,
--        FLIGHTNBR,
--        ACTION_USER,
--        ACTION_DATE,
--        DBMS_LOB.SUBSTR(CHANGE_DETAIL, 4000, 1) AS CHANGE_DETAIL
--   FROM T_PERMDETAIL_SC_ACTION_HISTORY
--  WHERE PERM_ID = :P_PERM_ID
--  ORDER BY ACTION_DATE DESC;
