-- Verify package update va trigger lich su SC.

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('PERM_PKG', 'TRG_T_PERMDETAIL_SC_ACTION_HIS')
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT NAME, TYPE, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME IN ('PERM_PKG', 'TRG_T_PERMDETAIL_SC_ACTION_HIS')
 ORDER BY NAME, SEQUENCE;

SELECT LINE, TEXT
  FROM USER_SOURCE
 WHERE NAME = 'PERM_PKG'
   AND TYPE = 'PACKAGE BODY'
   AND LINE BETWEEN
       (
           SELECT MIN(LINE)
             FROM USER_SOURCE
            WHERE NAME = 'PERM_PKG'
              AND TYPE = 'PACKAGE BODY'
              AND UPPER(TEXT) LIKE '%PROCEDURE PERMDETAIL_SC_UPDATE(%'
       )
       AND
       (
           SELECT MIN(LINE) + 180
             FROM USER_SOURCE
            WHERE NAME = 'PERM_PKG'
              AND TYPE = 'PACKAGE BODY'
              AND UPPER(TEXT) LIKE '%PROCEDURE PERMDETAIL_SC_UPDATE(%'
       )
 ORDER BY LINE;
