from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime, time

import oracledb

from models import FlightRecord, SlotRecord


class OracleDatabase:
    def __init__(self, host: str, port: int, service: str, user: str, password: str):
        self.connection = oracledb.connect(
            user=user,
            password=password,
            dsn=oracledb.makedsn(host, port, service_name=service),
        )

    def close(self) -> None:
        self.connection.close()

    def verify_schema(self) -> None:
        expected = {"ID", "Date", "CALLSIGN", "From", "To", "ETD", "ETA", "OPER"}
        cursor = self.connection.cursor()
        cursor.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'T_KHH'")
        actual = {row[0] for row in cursor}
        missing = expected - actual
        if missing:
            raise RuntimeError(f"Bảng T_KHH thiếu cột: {', '.join(sorted(missing))}")

    def ensure_slot_table(self) -> None:
        cursor = self.connection.cursor()
        cursor.execute("SELECT COUNT(*) FROM user_tables WHERE table_name = 'T_SLOT_AERO'")
        if cursor.fetchone()[0] == 0:
            cursor.execute('''
                CREATE TABLE T_SLOT_AERO (
                    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    ETD_ETA VARCHAR2(6),
                    CARRIE VARCHAR2(10),
                    AC VARCHAR2(10),
                    SEATS VARCHAR2(10),
                    FROM_AIRP VARCHAR2(4),
                    TO_AIRP VARCHAR2(4),
                    CALLSIGN VARCHAR2(10),
                    FLIGHT_DATE DATE,
                    AERO VARCHAR2(2)
                )
            ''')
        cursor.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'T_SLOT_AERO'")
        current = {row[0] for row in cursor}
        # Tương thích cấu trúc thử nghiệm cũ: sửa tên cột, không xóa dữ liệu.
        if "ETD_ETA" not in current and "ETA_ETD" in current:
            cursor.execute("ALTER TABLE T_SLOT_AERO RENAME COLUMN ETA_ETD TO ETD_ETA")
            current.remove("ETA_ETD")
            current.add("ETD_ETA")
        if "ID" not in current:
            cursor.execute("ALTER TABLE T_SLOT_AERO ADD (ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY)")
            cursor.execute("ALTER TABLE T_SLOT_AERO ADD CONSTRAINT PK_T_SLOT_AERO PRIMARY KEY (ID)")
            current.add("ID")
        expected = {"ID", "ETD_ETA", "CARRIE", "AC", "SEATS", "FROM_AIRP", "TO_AIRP", "CALLSIGN", "FLIGHT_DATE", "AERO"}
        cursor.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'T_SLOT_AERO'")
        missing = expected - {row[0] for row in cursor}
        if missing:
            raise RuntimeError(f"Bảng T_SLOT_AERO thiếu cột: {', '.join(sorted(missing))}")

    def import_khh(self, records: list[FlightRecord]) -> tuple[int, int]:
        if not records:
            return 0, 0
        cursor = self.connection.cursor()
        cursor.execute("SAVEPOINT before_khh_folder")
        try:
            dates = sorted({record.flight_date for record in records})
            placeholders = ",".join(f":{index + 1}" for index in range(len(dates)))
            cursor.execute(
                f'''SELECT "Date", CALLSIGN, "From", "To", ETD, ETA, OPER
                    FROM T_KHH WHERE TRUNC("Date") IN ({placeholders})''',
                [datetime.combine(value, time.min) for value in dates],
            )
            existing = {
                (row[0].date(), row[1], row[2], row[3], row[4], row[5], row[6])
                for row in cursor
            }
            pending = [record for record in records if record.key not in existing]
            rows = [
                (
                    datetime.combine(record.flight_date, time.min),
                    record.callsign,
                    record.origin,
                    record.destination,
                    record.etd,
                    record.eta,
                    record.operator,
                )
                for record in pending
            ]
            if rows:
                cursor.executemany(
                    '''INSERT INTO T_KHH ("Date", CALLSIGN, "From", "To", ETD, ETA, OPER)
                       VALUES (:1, :2, :3, :4, :5, :6, :7)''',
                    rows,
                )
            self.connection.commit()
            return len(rows), len(records) - len(rows)
        except Exception:
            cursor.execute("ROLLBACK TO SAVEPOINT before_khh_folder")
            self.connection.rollback()
            raise

    def import_slots(self, records: list[SlotRecord]) -> tuple[int, int]:
        if not records:
            return 0, 0
        cursor = self.connection.cursor()
        cursor.execute("SAVEPOINT before_slot_folder")
        try:
            dates = sorted({record.flight_date for record in records})
            placeholders = ",".join(f":{index + 1}" for index in range(len(dates)))
            cursor.execute(
                f'''SELECT ETD_ETA, CARRIE, AC, SEATS, FROM_AIRP, TO_AIRP, CALLSIGN, FLIGHT_DATE, AERO
                    FROM T_SLOT_AERO WHERE TRUNC(FLIGHT_DATE) IN ({placeholders})''',
                [datetime.combine(value, time.min) for value in dates],
            )
            existing = {
                (row[0] or "", row[1] or "", row[2] or "", row[3] or "", row[4] or "", row[5] or "", row[6] or "", row[7].date(), row[8] or "")
                for row in cursor
            }
            pending = [record for record in records if record.key not in existing]
            rows = [
                (record.etd_eta, record.carrier, record.aircraft, record.seats, record.from_airport,
                 record.to_airport, record.callsign or None, datetime.combine(record.flight_date, time.min), record.aero or None)
                for record in pending
            ]
            if rows:
                cursor.executemany(
                    '''INSERT INTO T_SLOT_AERO
                       (ETD_ETA, CARRIE, AC, SEATS, FROM_AIRP, TO_AIRP, CALLSIGN, FLIGHT_DATE, AERO)
                       VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)''', rows)
            self.connection.commit()
            return len(rows), len(records) - len(rows)
        except Exception:
            cursor.execute("ROLLBACK TO SAVEPOINT before_slot_folder")
            self.connection.rollback()
            raise

