//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjApplication.MessManagement
{
    public partial class LiveFireMessageAccepted
    {
    }
}
