-- Lưu lịch sử và chi tiết kết quả đối chiếu SLOT/KHH/Phép bay.
-- Script có thể chạy lại nhiều lần trên schema ATFM.

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE T_SLOT_COMPARE_RUN (
            ID NUMBER(18) NOT NULL,
            COMPARE_DATE DATE NOT NULL,
            CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
            UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
            CREATED_BY VARCHAR2(100),
            CONSTRAINT PK_SLOT_COMPARE_RUN PRIMARY KEY (ID),
            CONSTRAINT UQ_SLOT_COMPARE_RUN_DATE UNIQUE (COMPARE_DATE)
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE T_SLOT_COMPARE_RESULT (
            ID NUMBER(18) NOT NULL,
            RUN_ID NUMBER(18) NOT NULL,
            RESULT_TYPE VARCHAR2(3) NOT NULL,
            FLIGHT_DATE DATE NOT NULL,
            OPER VARCHAR2(10) NOT NULL,
            CALLSIGN VARCHAR2(30) NOT NULL,
            FROM_AIRP VARCHAR2(4),
            TO_AIRP VARCHAR2(4),
            ETD VARCHAR2(10),
            REMARK VARCHAR2(500),
            SOURCE_REF VARCHAR2(100),
            CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
            CONSTRAINT PK_SLOT_COMPARE_RESULT PRIMARY KEY (ID),
            CONSTRAINT FK_SLOT_COMPARE_RESULT_RUN FOREIGN KEY (RUN_ID)
                REFERENCES T_SLOT_COMPARE_RUN (ID) ON DELETE CASCADE,
            CONSTRAINT CK_SLOT_COMPARE_RESULT_TYPE CHECK (RESULT_TYPE IN (''KQ1'',''KQ2'',''KQ3'',''KQ4''))
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SLOT_COMPARE_RUN START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SLOT_COMPARE_RESULT START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SLOT_COMPARE_RESULT_FILTER ON T_SLOT_COMPARE_RESULT (RUN_ID, RESULT_TYPE, OPER)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
