//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjApplication.PlanMessage
{
    public partial class SendAMHSHistory
    {
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtFromDate;
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtToDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.GridView grdSource;
        protected global::CustomControl.CustomPaging CustomPaging1;
    }
}
