//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới chức năng hệ thống.
        /// </summary>
        internal static string AddNewsTittlePanelMenu {
            get {
                return ResourceManager.GetString("AddNewsTittlePanelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thành phố.
        /// </summary>
        internal static string AIG_City_Name {
            get {
                return ResourceManager.GetString("AIG_City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên trang.
        /// </summary>
        internal static string AIG_Languages_Name {
            get {
                return ResourceManager.GetString("AIG_Languages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã nước.
        /// </summary>
        internal static string AIG_ResultOld_EDIT_MAQG {
            get {
                return ResourceManager.GetString("AIG_ResultOld_EDIT_MAQG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của loại thi đấu.
        /// </summary>
        internal static string AIG_Sport_Cat_Name {
            get {
                return ResourceManager.GetString("AIG_Sport_Cat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên đề đã được dịch ngữ !.
        /// </summary>
        internal static string ALERT_NHANBAN_DANHMUCCHUYENDE {
            get {
                return ResourceManager.GetString("ALERT_NHANBAN_DANHMUCCHUYENDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string BA_LEHOI_BUTTON_THEMMOI {
            get {
                return ResourceManager.GetString("BA_LEHOI_BUTTON_THEMMOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng.
        /// </summary>
        internal static string BA_LEHOI_DANGBAI {
            get {
                return ResourceManager.GetString("BA_LEHOI_DANGBAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        internal static string BA_LEHOI_DIENGIAI {
            get {
                return ResourceManager.GetString("BA_LEHOI_DIENGIAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        internal static string BA_LEHOI_DUYET {
            get {
                return ResourceManager.GetString("BA_LEHOI_DUYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa danh mục.
        /// </summary>
        internal static string BA_LEHOI_EDIT_GROUPTEXT {
            get {
                return ResourceManager.GetString("BA_LEHOI_EDIT_GROUPTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        internal static string BA_LEHOI_HIENTHI {
            get {
                return ResourceManager.GetString("BA_LEHOI_HIENTHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string BA_LEHOI_HUYDANG {
            get {
                return ResourceManager.GetString("BA_LEHOI_HUYDANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string BA_LEHOI_MOTA {
            get {
                return ResourceManager.GetString("BA_LEHOI_MOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string BA_LEHOI_NAN {
            get {
                return ResourceManager.GetString("BA_LEHOI_NAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới danh mục.
        /// </summary>
        internal static string BA_LEHOI_NEW_GROUPTEXT {
            get {
                return ResourceManager.GetString("BA_LEHOI_NEW_GROUPTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên trang.
        /// </summary>
        internal static string BA_LEHOI_NGONNGU {
            get {
                return ResourceManager.GetString("BA_LEHOI_NGONNGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        internal static string BA_LEHOI_NGUOITAO {
            get {
                return ResourceManager.GetString("BA_LEHOI_NGUOITAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số báo.
        /// </summary>
        internal static string BA_LEHOI_SOBAO {
            get {
                return ResourceManager.GetString("BA_LEHOI_SOBAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số báo.
        /// </summary>
        internal static string BA_LEHOI_SOXB {
            get {
                return ResourceManager.GetString("BA_LEHOI_SOXB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string BA_LEHOI_SUA {
            get {
                return ResourceManager.GetString("BA_LEHOI_SUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string BA_LEHOI_TEN {
            get {
                return ResourceManager.GetString("BA_LEHOI_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        internal static string BA_LEHOI_TENDANHMUC {
            get {
                return ResourceManager.GetString("BA_LEHOI_TENDANHMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string BA_LEHOI_THEMMOI {
            get {
                return ResourceManager.GetString("BA_LEHOI_THEMMOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string BA_LEHOI_TIMKIEM {
            get {
                return ResourceManager.GetString("BA_LEHOI_TIMKIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục :.
        /// </summary>
        internal static string BA_LEHOI_TIMKIEM_DANHMUC {
            get {
                return ResourceManager.GetString("BA_LEHOI_TIMKIEM_DANHMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên trang : .
        /// </summary>
        internal static string BA_LEHOI_TIMKIEM_NN {
            get {
                return ResourceManager.GetString("BA_LEHOI_TIMKIEM_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề : .
        /// </summary>
        internal static string BA_LEHOI_TIMKIEM_TIEUDE {
            get {
                return ResourceManager.GetString("BA_LEHOI_TIMKIEM_TIEUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách các danh mục lễ hội.
        /// </summary>
        internal static string BA_LEHOI_TITLE {
            get {
                return ResourceManager.GetString("BA_LEHOI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        internal static string BA_LEHOI_USER {
            get {
                return ResourceManager.GetString("BA_LEHOI_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        internal static string BA_LEHOI_VITRI {
            get {
                return ResourceManager.GetString("BA_LEHOI_VITRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string BA_LEHOI_XOA {
            get {
                return ResourceManager.GetString("BA_LEHOI_XOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi hiệu đính.
        /// </summary>
        internal static string BA_QLND_CHECKER_SEND {
            get {
                return ResourceManager.GetString("BA_QLND_CHECKER_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn chỉnh.
        /// </summary>
        internal static string BA_QLND_COMP {
            get {
                return ResourceManager.GetString("BA_QLND_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày gửi.
        /// </summary>
        internal static string BA_QLND_DATE {
            get {
                return ResourceManager.GetString("BA_QLND_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download nội dung bài viết.
        /// </summary>
        internal static string BA_QLND_DOWNLOAD_TOOLTIP {
            get {
                return ResourceManager.GetString("BA_QLND_DOWNLOAD_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh  mục.
        /// </summary>
        internal static string BA_QLND_EVENT {
            get {
                return ResourceManager.GetString("BA_QLND_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi E-Mail cho hiệu đính.
        /// </summary>
        internal static string BA_QLND_GUI_EMAIL {
            get {
                return ResourceManager.GetString("BA_QLND_GUI_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên trang.
        /// </summary>
        internal static string BA_QLND_LANG {
            get {
                return ResourceManager.GetString("BA_QLND_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bài.
        /// </summary>
        internal static string BA_QLND_NEWS_NAME {
            get {
                return ResourceManager.GetString("BA_QLND_NEWS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi duyệt.
        /// </summary>
        internal static string BA_QLND_PUB_SEND {
            get {
                return ResourceManager.GetString("BA_QLND_PUB_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi duyệt xuất bản.
        /// </summary>
        internal static string BA_QLND_PUB_SEND_ED {
            get {
                return ResourceManager.GetString("BA_QLND_PUB_SEND_ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch bài.
        /// </summary>
        internal static string BA_QLND_TRANS {
            get {
                return ResourceManager.GetString("BA_QLND_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người gửi.
        /// </summary>
        internal static string BA_QLND_USER_SEND {
            get {
                return ResourceManager.GetString("BA_QLND_USER_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem/In.
        /// </summary>
        internal static string BA_QLND_VIEW_PRINT {
            get {
                return ResourceManager.GetString("BA_QLND_VIEW_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi E-Mail.
        /// </summary>
        internal static string BA_QNND_TRANS_EMAIL {
            get {
                return ResourceManager.GetString("BA_QNND_TRANS_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string BUTTON_ACCEPT {
            get {
                return ResourceManager.GetString("BUTTON_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string BUTTON_ACCEPTEXIT {
            get {
                return ResourceManager.GetString("BUTTON_ACCEPTEXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string BUTTON_ACCEPTNEWS {
            get {
                return ResourceManager.GetString("BUTTON_ACCEPTNEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; width=&apos;15px&apos; height=&apos;15px&apos; class=&apos;icon&apos; src=&apos;images/new.gif&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Thêm mới.
        /// </summary>
        internal static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        internal static string BUTTON_ChangesPass {
            get {
                return ResourceManager.GetString("BUTTON_ChangesPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; width=&apos;15px&apos; height=&apos;15px&apos; class=&apos;icon&apos; src=&apos;images/hsi_ni06.gif&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Hủy bỏ.
        /// </summary>
        internal static string BUTTON_EXIT {
            get {
                return ResourceManager.GetString("BUTTON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; width=&apos;15px&apos; height=&apos;15px&apos; class=&apos;icon&apos; src=&apos;images/document_new.png&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Phản hồi.
        /// </summary>
        internal static string BUTTON_FEEDBACK {
            get {
                return ResourceManager.GetString("BUTTON_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; class=&apos;icon&apos; src=&apos;Images/Icons/ForgotPassword.gif&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Quên mật khẩu.
        /// </summary>
        internal static string BUTTON_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi duyệt.
        /// </summary>
        internal static string BUTTON_GUIBAI {
            get {
                return ResourceManager.GetString("BUTTON_GUIBAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi hiệu đính.
        /// </summary>
        internal static string BUTTON_GUI_HIEUDINH {
            get {
                return ResourceManager.GetString("BUTTON_GUI_HIEUDINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file word.
        /// </summary>
        internal static string BUTTON_LOAD {
            get {
                return ResourceManager.GetString("BUTTON_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tin.
        /// </summary>
        internal static string BUTTON_LUU {
            get {
                return ResourceManager.GetString("BUTTON_LUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; width=&apos;15px&apos; height=&apos;15px&apos; class=&apos;icon&apos; src=&apos;images/document_new.png&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Thông báo.
        /// </summary>
        internal static string BUTTON_MESSAGE {
            get {
                return ResourceManager.GetString("BUTTON_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; width=&apos;15px&apos; height=&apos;15px&apos; class=&apos;icon&apos; src=&apos;images/save.gif&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Cập nhật.
        /// </summary>
        internal static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu giữ.
        /// </summary>
        internal static string BUTTON_SAVES {
            get {
                return ResourceManager.GetString("BUTTON_SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img id=&quot;imgTimkiem&quot; runat=&quot;server&quot; align=&quot;absMiddle&quot; alt=&quot;&quot; height=&quot;16&quot; src=&quot;Images/find.gif&quot; width=&quot;16&quot; border=&quot;0&quot; /&gt;&amp;nbsp;Tìm kiếm.
        /// </summary>
        internal static string BUTTON_SEARCH {
            get {
                return ResourceManager.GetString("BUTTON_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; width=&apos;15px&apos; height=&apos;15px&apos; class=&apos;icon&apos; src=&apos;images/save.gif&apos; /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Gửi.
        /// </summary>
        internal static string BUTTON_SEND {
            get {
                return ResourceManager.GetString("BUTTON_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string BUTTON_SIGNIN {
            get {
                return ResourceManager.GetString("BUTTON_SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits.
        /// </summary>
        internal static string BUTTON_SIGOUT {
            get {
                return ResourceManager.GetString("BUTTON_SIGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng đăng.
        /// </summary>
        internal static string BUTTON_STOP {
            get {
                return ResourceManager.GetString("BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại.
        /// </summary>
        internal static string BUTTON_TRABAI {
            get {
                return ResourceManager.GetString("BUTTON_TRABAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại.
        /// </summary>
        internal static string BUTTON_TRALAIGUIBAI {
            get {
                return ResourceManager.GetString("BUTTON_TRALAIGUIBAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn nhóm người dùng.
        /// </summary>
        internal static string CBO_LISTGROUP {
            get {
                return ResourceManager.GetString("CBO_LISTGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn người dùng.
        /// </summary>
        internal static string CBO_LISTUSER {
            get {
                return ResourceManager.GetString("CBO_LISTUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change pass.
        /// </summary>
        internal static string CHANGE_PASS {
            get {
                return ResourceManager.GetString("CHANGE_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh thành phố :.
        /// </summary>
        internal static string CITY_EDIT_ANHTP {
            get {
                return ResourceManager.GetString("CITY_EDIT_ANHTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả thành phố :.
        /// </summary>
        internal static string CITY_EDIT_MOTA {
            get {
                return ResourceManager.GetString("CITY_EDIT_MOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Gửi thông báo đến đơn vị.
        /// </summary>
        internal static string FEEDBACK_TITLE_EDIT {
            get {
                return ResourceManager.GetString("FEEDBACK_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Gửi thông báo đến ban chức năng.
        /// </summary>
        internal static string FEEDBACK_TITLE_EDIT_BAN {
            get {
                return ResourceManager.GetString("FEEDBACK_TITLE_EDIT_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Thông tin phản hồi của các đơn vị.
        /// </summary>
        internal static string FEEDBACK_TITLE_LIST {
            get {
                return ResourceManager.GetString("FEEDBACK_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Thông báo của ban chức năng.
        /// </summary>
        internal static string FEEDBACK_TITLE_LIST_BAN {
            get {
                return ResourceManager.GetString("FEEDBACK_TITLE_LIST_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đính kèm một tệp khác.
        /// </summary>
        internal static string FUA_ADD {
            get {
                return ResourceManager.GetString("FUA_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string FUA_DELETE {
            get {
                return ResourceManager.GetString("FUA_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string GRIDTITTLDELETE {
            get {
                return ResourceManager.GetString("GRIDTITTLDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người tham dự đại hội.
        /// </summary>
        internal static string GRIDTITTLEDanhSachAIG_Participant {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachAIG_Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nơi thi đấu.
        /// </summary>
        internal static string GRIDTITTLEDanhSachAIG_Venues {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachAIG_Venues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách các môn thể thao.
        /// </summary>
        internal static string GRIDTITTLEDanhSachCacMonTheThao {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachCacMonTheThao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phân loại theo nhóm thi đấu.
        /// </summary>
        internal static string GRIDTITTLEDanhSachSport_Cat {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachSport_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết môn thể thao theo từng chỉ mục.
        /// </summary>
        internal static string GRIDTITTLEDanhSachSport_Desc {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachSport_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn thi đấu thuộc môn thể thao cụ thể.
        /// </summary>
        internal static string GRIDTITTLEDanhSachSport_Details {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachSport_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các nội dung thi đấu được phân loại theo nội dung và nhóm, kiểu thi đấu.
        /// </summary>
        internal static string GRIDTITTLEDanhSachSport_Event {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachSport_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Sport_Index_Name.
        /// </summary>
        internal static string GRIDTITTLEDanhSachSport_INdexName {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachSport_INdexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thông tin người dùng.
        /// </summary>
        internal static string GRIDTITTLEDanhSachThongTinNguoiDung {
            get {
                return ResourceManager.GetString("GRIDTITTLEDanhSachThongTinNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string GRIDTITTLEDIT {
            get {
                return ResourceManager.GetString("GRIDTITTLEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin người dùng.
        /// </summary>
        internal static string GRIDTITTLEEDITNguoiDung {
            get {
                return ResourceManager.GetString("GRIDTITTLEEDITNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng:.
        /// </summary>
        internal static string GRIDTITTLEGroup {
            get {
                return ResourceManager.GetString("GRIDTITTLEGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string GRIDTITTLERoleMoTa {
            get {
                return ResourceManager.GetString("GRIDTITTLERoleMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền danh mục.
        /// </summary>
        internal static string GRIDTITTLERolePhanQuyen {
            get {
                return ResourceManager.GetString("GRIDTITTLERolePhanQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        internal static string GRIDTITTLERoleTenDanhMuc {
            get {
                return ResourceManager.GetString("GRIDTITTLERoleTenDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string GRIDTITTLESEARCH {
            get {
                return ResourceManager.GetString("GRIDTITTLESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        internal static string GRIDTITTLETenNhom {
            get {
                return ResourceManager.GetString("GRIDTITTLETenNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới người dùng.
        /// </summary>
        internal static string GRIDTITTLEThemMoiNguoiDung {
            get {
                return ResourceManager.GetString("GRIDTITTLEThemMoiNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thông tin nhóm người dùng.
        /// </summary>
        internal static string GRIDTITTLEThongTinGroup {
            get {
                return ResourceManager.GetString("GRIDTITTLEThongTinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền nhóm người dùng: .
        /// </summary>
        internal static string GRIDTITTLEThongTinGroupROLE {
            get {
                return ResourceManager.GetString("GRIDTITTLEThongTinGroupROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Cập nhật thông tin nhóm.
        /// </summary>
        internal static string GROUP_TITLE_EDIT {
            get {
                return ResourceManager.GetString("GROUP_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Danh sách thông tin nhóm người dùng.
        /// </summary>
        internal static string GROUP_TITLE_LIST {
            get {
                return ResourceManager.GetString("GROUP_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Phân quyền nhóm người dùng.
        /// </summary>
        internal static string GROUP_TITLE_ROLE {
            get {
                return ResourceManager.GetString("GROUP_TITLE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thành phố :.
        /// </summary>
        internal static string HOTELS_EDIT_CHONTP {
            get {
                return ResourceManager.GetString("HOTELS_EDIT_CHONTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả :.
        /// </summary>
        internal static string HOTELS_EDIT_MOTA {
            get {
                return ResourceManager.GetString("HOTELS_EDIT_MOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string LABEL_DELETE {
            get {
                return ResourceManager.GetString("LABEL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string LABEL_EDIT {
            get {
                return ResourceManager.GetString("LABEL_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Chuyên trang.
        /// </summary>
        internal static string LABEL_LANGE_DANHSACH {
            get {
                return ResourceManager.GetString("LABEL_LANGE_DANHSACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string LABEL_LANG_GHICHU {
            get {
                return ResourceManager.GetString("LABEL_LANG_GHICHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hiệu.
        /// </summary>
        internal static string LABEL_LANG_KYHIEU {
            get {
                return ResourceManager.GetString("LABEL_LANG_KYHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Chuyên trang.
        /// </summary>
        internal static string LABEL_LANG_TEN {
            get {
                return ResourceManager.GetString("LABEL_LANG_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&lt;span class=&quot;req_Field&quot;&gt;(*)&lt;/span&gt;.
        /// </summary>
        internal static string LABEL_RED_START {
            get {
                return ResourceManager.GetString("LABEL_RED_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;u&gt;- Ghi chú:&lt;/u&gt; &amp;nbsp;Các ô có đánh dấu &lt;span class=&quot;req_Field&quot;&gt;*&lt;/span&gt; là trường
        ///                    bắt buộc phải nhập..
        /// </summary>
        internal static string LABEL_REQUIRE_FIELDS {
            get {
                return ResourceManager.GetString("LABEL_REQUIRE_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string LABEL_SEARCH {
            get {
                return ResourceManager.GetString("LABEL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết đã được dịch sang Chuyên trang này rồi!.
        /// </summary>
        internal static string LANQUAGE_ALERT {
            get {
                return ResourceManager.GetString("LANQUAGE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nên dịch ngữ từ Chuyên trang tiếng việt !.
        /// </summary>
        internal static string LANQUAGE_ALERT_EXITS {
            get {
                return ResourceManager.GetString("LANQUAGE_ALERT_EXITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên trang.
        /// </summary>
        internal static string lblNgonNguALL {
            get {
                return ResourceManager.GetString("lblNgonNguALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NewEditor/ListEditor.aspx?Menu_ID=8.
        /// </summary>
        internal static string lblPhanQuyenPhongVien {
            get {
                return ResourceManager.GetString("lblPhanQuyenPhongVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm báo chí - MPC.
        /// </summary>
        internal static string LOGIN_CUSTOMER {
            get {
                return ResourceManager.GetString("LOGIN_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên đăng nhập và mật khẩu. Sau đó nhấn nút &quot;Đăng nhập&quot; để vào trong trang quản lý website..
        /// </summary>
        internal static string LOGIN_DESC {
            get {
                return ResourceManager.GetString("LOGIN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công!.
        /// </summary>
        internal static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ mật khẩu.
        /// </summary>
        internal static string LOGIN_REMEMBER {
            get {
                return ResourceManager.GetString("LOGIN_REMEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP HỆ THỐNG.
        /// </summary>
        internal static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên truy cập.
        /// </summary>
        internal static string LOGIN_USERNAME {
            get {
                return ResourceManager.GetString("LOGIN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục.
        /// </summary>
        internal static string MenuQuanLyDanhMucTittle {
            get {
                return ResourceManager.GetString("MenuQuanLyDanhMucTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thông tin phòng ban.
        /// </summary>
        internal static string MENU_TITLE_Department {
            get {
                return ResourceManager.GetString("MENU_TITLE_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thông tin phòng ban.
        /// </summary>
        internal static string MENU_TITLE_DepartmentAdd {
            get {
                return ResourceManager.GetString("MENU_TITLE_DepartmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Cập nhật thông tin chức năng.
        /// </summary>
        internal static string MENU_TITLE_EDIT {
            get {
                return ResourceManager.GetString("MENU_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;&amp;nbsp;Danh sách thông tin chức năng hiện có.
        /// </summary>
        internal static string MENU_TITLE_LIST {
            get {
                return ResourceManager.GetString("MENU_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Cập nhật thông tin nhóm văn bản.
        /// </summary>
        internal static string NHOMVANBAN_TITLE_EDIT {
            get {
                return ResourceManager.GetString("NHOMVANBAN_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp; Danh mục nhóm văn bản.
        /// </summary>
        internal static string NHOMVANBAN_TITLE_LIST {
            get {
                return ResourceManager.GetString("NHOMVANBAN_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chi tiết :.
        /// </summary>
        internal static string NOC_DETAIL_DESCRIPTION {
            get {
                return ResourceManager.GetString("NOC_DETAIL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo uỷ ban :.
        /// </summary>
        internal static string NOC_DETAIL_EDIT_LOGO {
            get {
                return ResourceManager.GetString("NOC_DETAIL_EDIT_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách sạn :.
        /// </summary>
        internal static string NOC_EDIT_CHONHOTEL {
            get {
                return ResourceManager.GetString("NOC_EDIT_CHONHOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm người dùng.
        /// </summary>
        internal static string PANELEDITGROUPNAME {
            get {
                return ResourceManager.GetString("PANELEDITGROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhóm người dùng.
        /// </summary>
        internal static string PANELTHEMMOIGROUPNAME {
            get {
                return ResourceManager.GetString("PANELTHEMMOIGROUPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string PNLTITTLEGROUPTEXTEDITADD {
            get {
                return ResourceManager.GetString("PNLTITTLEGROUPTEXTEDITADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string PNLTITTLEGROUPTEXTEDITEDIT {
            get {
                return ResourceManager.GetString("PNLTITTLEGROUPTEXTEDITEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi biên tập.
        /// </summary>
        internal static string QLND_BUTTON_APPROVE {
            get {
                return ResourceManager.GetString("QLND_BUTTON_APPROVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết bài mới.
        /// </summary>
        internal static string QLND_BUTTON_CREATE {
            get {
                return ResourceManager.GetString("QLND_BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bài viết.
        /// </summary>
        internal static string QLND_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("QLND_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục cha:.
        /// </summary>
        internal static string QLTT_CHUYENMUC_CHUYENMUCCHA {
            get {
                return ResourceManager.GetString("QLTT_CHUYENMUC_CHUYENMUCCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục cha:.
        /// </summary>
        internal static string QLTT_CHUYENMUC_CHUYENMUCCHA1 {
            get {
                return ResourceManager.GetString("QLTT_CHUYENMUC_CHUYENMUCCHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục cha :.
        /// </summary>
        internal static string QLTT_CHUYENMUC_CHUYENMUCCHA11 {
            get {
                return ResourceManager.GetString("QLTT_CHUYENMUC_CHUYENMUCCHA11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chuyên muc:.
        /// </summary>
        internal static string QLTT_CHUYENMUC_TENCHUYENMUC {
            get {
                return ResourceManager.GetString("QLTT_CHUYENMUC_TENCHUYENMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề :.
        /// </summary>
        internal static string QLTT_TINTUCLIST_TIEUDECM {
            get {
                return ResourceManager.GetString("QLTT_TINTUCLIST_TIEUDECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đề tài:.
        /// </summary>
        internal static string QLTT_TINTUCLIST_TIEUDECM1 {
            get {
                return ResourceManager.GetString("QLTT_TINTUCLIST_TIEUDECM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đính kèm.
        /// </summary>
        internal static string QLTT_TINTUC_ANHDINHKEM {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_ANHDINHKEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh tin bài:.
        /// </summary>
        internal static string QLTT_TINTUC_ANHTINBAI {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_ANHTINBAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đính kèm.
        /// </summary>
        internal static string QLTT_TINTUC_ANHTINBAI_VIDEO {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_ANHTINBAI_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên đề.
        /// </summary>
        internal static string QLTT_TINTUC_CHUYENDE {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_CHUYENDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        internal static string QLTT_TINTUC_CHUYENMUC {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_CHUYENMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa điểm thi đấu.
        /// </summary>
        internal static string QLTT_TINTUC_DIADIEMTHIDAU {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_DIADIEMTHIDAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn môn thể thao.
        /// </summary>
        internal static string QLTT_TINTUC_MONTHETHAO {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_MONTHETHAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung:.
        /// </summary>
        internal static string QLTT_TINTUC_NOIDUNGTIN {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_NOIDUNGTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn video.
        /// </summary>
        internal static string QLTT_TINTUC_PATH_VIDEO {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_PATH_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn quốc gia.
        /// </summary>
        internal static string QLTT_TINTUC_TENQG {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TENQG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tiêu đề.
        /// </summary>
        internal static string QLTT_TINTUC_TIEUDE {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TIEUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề English.
        /// </summary>
        internal static string QLTT_TINTUC_TIEUDE_ENG {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TIEUDE_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề tiếng việt.
        /// </summary>
        internal static string QLTT_TINTUC_TIEUDE_VIETNAM {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TIEUDE_VIETNAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapo:.
        /// </summary>
        internal static string QLTT_TINTUC_TOMTAT {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TOMTAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt English.
        /// </summary>
        internal static string QLTT_TINTUC_TOMTAT_ENG {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TOMTAT_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt tiếng việt.
        /// </summary>
        internal static string QLTT_TINTUC_TOMTAT_VIETNAM {
            get {
                return ResourceManager.GetString("QLTT_TINTUC_TOMTAT_VIETNAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm thi đấu.
        /// </summary>
        internal static string Sport_EventCat_IDEdit {
            get {
                return ResourceManager.GetString("Sport_EventCat_IDEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã môn thi đấu chi tiết.
        /// </summary>
        internal static string Sport_EventDetail_IDEdit {
            get {
                return ResourceManager.GetString("Sport_EventDetail_IDEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thi đấu đối kháng hay biểu diễn.
        /// </summary>
        internal static string Sport_EventExercise_Type_ID {
            get {
                return ResourceManager.GetString("Sport_EventExercise_Type_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nội dung thi đấu.
        /// </summary>
        internal static string Sport_EventNameEdit {
            get {
                return ResourceManager.GetString("Sport_EventNameEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kiểu thi đấu.
        /// </summary>
        internal static string Sport_EventTeam_Type_IDEdit {
            get {
                return ResourceManager.GetString("Sport_EventTeam_Type_IDEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã môn thi này đã tồn tại.
        /// </summary>
        internal static string Sport_ValidateExits_Code {
            get {
                return ResourceManager.GetString("Sport_ValidateExits_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã môn thi đấu đã tồn tại.
        /// </summary>
        internal static string Sport_ValidateExits_CodeDetails {
            get {
                return ResourceManager.GetString("Sport_ValidateExits_CodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức năng.
        /// </summary>
        internal static string SYSTEM_EDITMENUTenChucNang {
            get {
                return ResourceManager.GetString("SYSTEM_EDITMENUTenChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string SYSTEM_GridTiitleDelete {
            get {
                return ResourceManager.GetString("SYSTEM_GridTiitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string SYSTEM_GridTiitleDuongDan {
            get {
                return ResourceManager.GetString("SYSTEM_GridTiitleDuongDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string SYSTEM_GridTiitleEdit {
            get {
                return ResourceManager.GetString("SYSTEM_GridTiitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        internal static string SYSTEM_GridTiitleTenDanhMuc {
            get {
                return ResourceManager.GetString("SYSTEM_GridTiitleTenDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng cha.
        /// </summary>
        internal static string SYSTEM_MENU_ChucNangCha {
            get {
                return ResourceManager.GetString("SYSTEM_MENU_ChucNangCha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh minh họa.
        /// </summary>
        internal static string SYSTEM_MENU_EDITAnhMinhHoa {
            get {
                return ResourceManager.GetString("SYSTEM_MENU_EDITAnhMinhHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string SYSTEM_MENU_EDITDuongDan {
            get {
                return ResourceManager.GetString("SYSTEM_MENU_EDITDuongDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        internal static string SYSTEM_MENU_EDITHienThi {
            get {
                return ResourceManager.GetString("SYSTEM_MENU_EDITHienThi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string SYSTEM_MENU_EDITMoTa {
            get {
                return ResourceManager.GetString("SYSTEM_MENU_EDITMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        internal static string SYSTEM_MENU_EDITThuTu {
            get {
                return ResourceManager.GetString("SYSTEM_MENU_EDITThuTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài đang xử lý tại PV.
        /// </summary>
        internal static string System_StatusDocumentsALL1 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho hiệu đính.
        /// </summary>
        internal static string System_StatusDocumentsALL10 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài đã bị xóa.
        /// </summary>
        internal static string System_StatusDocumentsALL11 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn chỉnh ngữ đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL12 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho Hoàn chỉnh ngữ.
        /// </summary>
        internal static string System_StatusDocumentsALL13 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ duyệt xuất bản.
        /// </summary>
        internal static string System_StatusDocumentsALL14 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho thư ký.
        /// </summary>
        internal static string System_StatusDocumentsALL15 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng ban  đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL16 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài đã được xuất bản.
        /// </summary>
        internal static string System_StatusDocumentsALL17 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho phóng viên.
        /// </summary>
        internal static string System_StatusDocumentsALL2 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài đang xử lý tại PV.
        /// </summary>
        internal static string System_StatusDocumentsALL20 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại bài cho PV.
        /// </summary>
        internal static string System_StatusDocumentsALL21 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi TKTS.
        /// </summary>
        internal static string System_StatusDocumentsALL22 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại bài cho TKTS.
        /// </summary>
        internal static string System_StatusDocumentsALL23 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Họa sĩ trình bày.
        /// </summary>
        internal static string System_StatusDocumentsALL24 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại bài cho Họa sĩ trình bày.
        /// </summary>
        internal static string System_StatusDocumentsALL25 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Biên dịch ngữ.
        /// </summary>
        internal static string System_StatusDocumentsALL26 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại biên dịch ngữ.
        /// </summary>
        internal static string System_StatusDocumentsALL27 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi hiệu đính.
        /// </summary>
        internal static string System_StatusDocumentsALL28 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại bài cho hiệu đính.
        /// </summary>
        internal static string System_StatusDocumentsALL29 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKTS đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL3 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Hoàn chỉnh ngữ.
        /// </summary>
        internal static string System_StatusDocumentsALL30 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại bài cho Hoàn chỉnh ngữ.
        /// </summary>
        internal static string System_StatusDocumentsALL31 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi DXB.
        /// </summary>
        internal static string System_StatusDocumentsALL32 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi trả lại bài cho DXB.
        /// </summary>
        internal static string System_StatusDocumentsALL33 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi chờ DXB.
        /// </summary>
        internal static string System_StatusDocumentsALL34 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi bài đã được xuất bản.
        /// </summary>
        internal static string System_StatusDocumentsALL35 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho TKTS.
        /// </summary>
        internal static string System_StatusDocumentsALL4 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họa sĩ trình bày đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL5 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho Họa sĩ trình bầy.
        /// </summary>
        internal static string System_StatusDocumentsALL6 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biên dịch ngữ đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL7 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng biên tập đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL70 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại bài cho trưởng ban.
        /// </summary>
        internal static string System_StatusDocumentsALL71 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại biên dịch ngữ.
        /// </summary>
        internal static string System_StatusDocumentsALL8 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu đính đang xử lý.
        /// </summary>
        internal static string System_StatusDocumentsALL9 {
            get {
                return ResourceManager.GetString("System_StatusDocumentsALL9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Cập nhật thông tin văn bản.
        /// </summary>
        internal static string TBM_TITLE_EDIT {
            get {
                return ResourceManager.GetString("TBM_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Danh mục văn bản.
        /// </summary>
        internal static string TBM_TITLE_LIST {
            get {
                return ResourceManager.GetString("TBM_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;13&quot; src=&quot;Images/arrow_d.gif&quot; width=&quot;15&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;Tên văn bản.
        /// </summary>
        internal static string TEPMAUBIEU_TITLE {
            get {
                return ResourceManager.GetString("TEPMAUBIEU_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa Chuyên trang.
        /// </summary>
        internal static string TOOLTIP_SUA_NN {
            get {
                return ResourceManager.GetString("TOOLTIP_SUA_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Chuyên trang.
        /// </summary>
        internal static string TOOLTIP_XOA_NN {
            get {
                return ResourceManager.GetString("TOOLTIP_XOA_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại thi đấu:.
        /// </summary>
        internal static string txtSearchNameTenLoaiThidau {
            get {
                return ResourceManager.GetString("txtSearchNameTenLoaiThidau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nội dung thi đấu.
        /// </summary>
        internal static string txtSearchNameTenNoiDungThiDau {
            get {
                return ResourceManager.GetString("txtSearchNameTenNoiDungThiDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string T_NEWSCHUYENDE_TKTS_LIST {
            get {
                return ResourceManager.GetString("T_NEWSCHUYENDE_TKTS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tác giả:.
        /// </summary>
        internal static string T_NEWS_CHUYENDE_EDIT_AUTHORNAME {
            get {
                return ResourceManager.GetString("T_NEWS_CHUYENDE_EDIT_AUTHORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú thích:.
        /// </summary>
        internal static string T_NEWS_CHUYENDE_EDIT_COMMENTS {
            get {
                return ResourceManager.GetString("T_NEWS_CHUYENDE_EDIT_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức quan trọng:.
        /// </summary>
        internal static string T_NEWS_CHUYENDE_EDIT_DOUUTIEN {
            get {
                return ResourceManager.GetString("T_NEWS_CHUYENDE_EDIT_DOUUTIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        internal static string UpdateSuccessfully {
            get {
                return ResourceManager.GetString("UpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới người tham dự đại hội.
        /// </summary>
        internal static string UpdateTittlePanelAIG_ParticipantAdd {
            get {
                return ResourceManager.GetString("UpdateTittlePanelAIG_ParticipantAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa người tham dự đại hội.
        /// </summary>
        internal static string UpdateTittlePanelAIG_ParticipantEdit {
            get {
                return ResourceManager.GetString("UpdateTittlePanelAIG_ParticipantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chức năng hệ thống.
        /// </summary>
        internal static string UpdateTittlePanelMenu {
            get {
                return ResourceManager.GetString("UpdateTittlePanelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UPLOAD_PATH {
            get {
                return ResourceManager.GetString("UPLOAD_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên.
        /// </summary>
        internal static string USER_FULLNAME {
            get {
                return ResourceManager.GetString("USER_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Cập nhật thông tin người dùng.
        /// </summary>
        internal static string USER_TITLE_EDIT {
            get {
                return ResourceManager.GetString("USER_TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Gán nhóm người dùng.
        /// </summary>
        internal static string USER_TITLE_GROUP {
            get {
                return ResourceManager.GetString("USER_TITLE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Danh sách thông tin người dùng.
        /// </summary>
        internal static string USER_TITLE_LIST {
            get {
                return ResourceManager.GetString("USER_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img height=&quot;42&quot; src=&quot;Images/chuyenmuc.gif&quot; width=&quot;42&quot; align=&quot;absMiddle&quot; border=&quot;0&quot;&gt;&amp;nbsp;&amp;nbsp;Phân quyền người dùng.
        /// </summary>
        internal static string USER_TITLE_ROLE {
            get {
                return ResourceManager.GetString("USER_TITLE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên.
        /// </summary>
        internal static string USER_TITLE_ROLETHANHVIEN {
            get {
                return ResourceManager.GetString("USER_TITLE_ROLETHANHVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên thuộc nhóm.
        /// </summary>
        internal static string USER_TITLE_ROLETHANHVIENTHUOCNHOM {
            get {
                return ResourceManager.GetString("USER_TITLE_ROLETHANHVIENTHUOCNHOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền theo nhóm cho người dùng: .
        /// </summary>
        internal static string USER_TITLE_ROLEWITDHGROUP {
            get {
                return ResourceManager.GetString("USER_TITLE_ROLEWITDHGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền chức năng người dùng: .
        /// </summary>
        internal static string USER_TITLE_ROLEWITDHMENU {
            get {
                return ResourceManager.GetString("USER_TITLE_ROLEWITDHMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang {0}/{1} ({2} bản ghi).
        /// </summary>
        internal static string Utility_CurrentPage_text {
            get {
                return ResourceManager.GetString("Utility_CurrentPage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |&lt;.
        /// </summary>
        internal static string Utility_Pager_firstButton {
            get {
                return ResourceManager.GetString("Utility_Pager_firstButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;|.
        /// </summary>
        internal static string Utility_Pager_lastButton {
            get {
                return ResourceManager.GetString("Utility_Pager_lastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string Utility_Pager_nextButton {
            get {
                return ResourceManager.GetString("Utility_Pager_nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string Utility_Pager_previousButton {
            get {
                return ResourceManager.GetString("Utility_Pager_previousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập tên của loại thi đấu.
        /// </summary>
        internal static string ValidateChuaNhapTenCuaLoaiTHiDau {
            get {
                return ResourceManager.GetString("ValidateChuaNhapTenCuaLoaiTHiDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn thành phố.
        /// </summary>
        internal static string ValidateCityNot {
            get {
                return ResourceManager.GetString("ValidateCityNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa không?.
        /// </summary>
        internal static string ValidateDeleteConfirmPublic {
            get {
                return ResourceManager.GetString("ValidateDeleteConfirmPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn Chuyên trang.
        /// </summary>
        internal static string ValidateLanguagesNot {
            get {
                return ResourceManager.GetString("ValidateLanguagesNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập mã nhóm thi đấu chi tiết.
        /// </summary>
        internal static string ValidateSport_EventCat_IDEdit {
            get {
                return ResourceManager.GetString("ValidateSport_EventCat_IDEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn mã môn thi đấu chi tiết.
        /// </summary>
        internal static string ValidateSport_EventDetail_IDEdit {
            get {
                return ResourceManager.GetString("ValidateSport_EventDetail_IDEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập tên nội dung thi đấu.
        /// </summary>
        internal static string ValidateSport_Event_Name {
            get {
                return ResourceManager.GetString("ValidateSport_Event_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã thêm mới thành công.
        /// </summary>
        internal static string VALIDATE_ADDNEWS {
            get {
                return ResourceManager.GetString("VALIDATE_ADDNEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu này đã tồn tại.
        /// </summary>
        internal static string VALIDATE_MenuExits {
            get {
                return ResourceManager.GetString("VALIDATE_MenuExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã thêm mới nhóm người dùng thành công..
        /// </summary>
        internal static string VALIDATE_NHOMNGUOIDUNG_AddNews {
            get {
                return ResourceManager.GetString("VALIDATE_NHOMNGUOIDUNG_AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng đã tồn tại..
        /// </summary>
        internal static string VALIDATE_NHOMNGUOIDUNG_EXIT {
            get {
                return ResourceManager.GetString("VALIDATE_NHOMNGUOIDUNG_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên truy cập đã tồn tại.
        /// </summary>
        internal static string VALIDATE_USERNAMEExits {
            get {
                return ResourceManager.GetString("VALIDATE_USERNAMEExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên truy cập đã có người sử dụng.
        /// </summary>
        internal static string VALIDATE_USER_EXIT {
            get {
                return ResourceManager.GetString("VALIDATE_USER_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên truy cập phải khác rỗng!.
        /// </summary>
        internal static string VALIDATE_USER_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATE_USER_REQUIRED", resourceCulture);
            }
        }
    }
}
