using System.Collections.Generic;

namespace QLB.Info
{
    public class FlightAnalyticsRequest { public string FromDate { get; set; } public string ToDate { get; set; } public string Airport { get; set; } public string Oper { get; set; } public string Purpose { get; set; } public bool CurrentDay { get; set; } public string Period { get; set; } }
    public class FlightAnalyticsRow { public string Callsign { get; set; } public string Oper { get; set; } public string Registration { get; set; } public string PermType { get; set; } public string FromAirp { get; set; } public string ToAirp { get; set; } public string AtdDay { get; set; } public string AtaDay { get; set; } public string EobtDay { get; set; } public string Status { get; set; } public string FlightDate { get; set; } public string CraftType { get; set; } public string Route { get; set; } public string PermitNbr { get; set; } public string Category { get; set; } }
    public class AirportTrafficRow { public string Code { get; set; } public int Departures { get; set; } public int Arrivals { get; set; } public int Total { get; set; } }
    public class FlightStatusRateResponse { public string Source { get; set; } public int Total { get; set; } public int Finished { get; set; } public int Cancel { get; set; } public int Delay { get; set; } public int Wait { get; set; } public List<FlightAnalyticsRow> Flights { get; set; } }
    public class FlightOperationOverviewResponse { public string Source { get; set; } public int Total { get; set; } public int Finished { get; set; } public int Delay { get; set; } public int AirportCount { get; set; } public int TotalDepartures { get; set; } public int TotalArrivals { get; set; } public List<AirportTrafficRow> Airports { get; set; } public List<FlightAnalyticsRow> Flights { get; set; } }
    public class FlightTrendResponse { public string Source { get; set; } public string Period { get; set; } public string CurrentFrom { get; set; } public string CurrentTo { get; set; } public string PreviousFrom { get; set; } public string PreviousTo { get; set; } public int CurrentTotal { get; set; } public int PreviousTotal { get; set; } public int CurrentFinished { get; set; } public int CurrentDelay { get; set; } public int Difference { get; set; } public double ChangePercent { get; set; } public List<string> Labels { get; set; } public List<int> Current { get; set; } public List<int> Previous { get; set; } }
    public class CivilFlightSummaryResponse { public string Source { get; set; } public int Total { get; set; } public int Domestic { get; set; } public int International { get; set; } public int Finished { get; set; } public int Delay { get; set; } public int Cancel { get; set; } public int Wait { get; set; } public double OnTimePercent { get; set; } public List<AirportTrafficRow> Airports { get; set; } public List<FlightAnalyticsRow> Flights { get; set; } }
    public class MilitaryFlightRow { public string PType { get; set; } public string FromAirp { get; set; } public string ToAirp { get; set; } public string Etd { get; set; } public string Eta { get; set; } public string Atd { get; set; } public string Ata { get; set; } public string Purpose { get; set; } public string FlightDate { get; set; } }
    public class MilitaryFlightResponse { public string Source { get; set; } public int Total { get; set; } public List<string> Airports { get; set; } public List<string> Purposes { get; set; } public List<MilitaryFlightRow> Flights { get; set; } }
    public class ChartReportResponse { public FlightStatusRateResponse Status { get; set; } public FlightOperationOverviewResponse Overview { get; set; } public FlightTrendResponse Trend { get; set; } }
}
